import type { RouteRecordRaw } from 'vue-router'
import { PERMISSIONS } from '@/shared/constants/permissions'

export const routes: RouteRecordRaw[] = [
  {
    path: '/',
    name: 'login',
    component: () => import('@/pages/index.vue'),
    meta: { requiresAuth: false, title: '登录' },
  },
  {
    path: '/activate',
    name: 'activate-account',
    component: () => import('@/pages/activate.vue'),
    meta: { requiresAuth: false, title: '激活账号' },
  },
  {
    path: '/forgot-password',
    name: 'forgot-password',
    component: () => import('@/pages/forgot-password.vue'),
    meta: { requiresAuth: false, title: '找回密码' },
  },
  {
    path: '/reset-password',
    name: 'reset-password',
    component: () => import('@/pages/reset-password.vue'),
    meta: { requiresAuth: false, title: '重置密码' },
  },
  {
    path: '/verify-contact',
    name: 'verify-contact',
    component: () => import('@/pages/verify-contact.vue'),
    meta: { requiresAuth: false, title: '验证联系方式' },
  },
  {
    path: '/first-password-change',
    name: 'first-password-change',
    component: () => import('@/pages/first-password-change.vue'),
    meta: {
      requiresAuth: true,
      title: '首次登录修改密码',
      allowDuringPasswordChange: true,
    },
  },
  {
    path: '/user-management-gate',
    name: 'user-management-gate',
    component: () => import('@/pages/user-management-gate.vue'),
    meta: {
      requiresAuth: true,
      title: '用户管理状态',
      allowDuringUserManagementGate: true,
    },
  },
  {
    path: '/dashboard',
    name: 'dashboard',
    component: () => import('@/layouts/DashboardLayout.vue'),
    meta: { requiresAuth: true, title: '仪表盘' },
    children: [
      {
        path: '',
        name: 'dashboard-statistic',
        component: () => import('@/pages/dashboard/index.vue'),
        meta: {
          requiresAuth: true,
          title: '统计',
          activeMenu: '/dashboard',
          permission: PERMISSIONS.statistic.view,
        },
      },
      {
        path: 'profile',
        name: 'profile',
        component: () => import('@/pages/dashboard/profile.vue'),
        meta: {
          requiresAuth: true,
          title: '个人中心',
          activeMenu: '/dashboard/profile',
          allowDuringPendingAdminSetup: true,
        },
      },
      {
        path: 'ai',
        name: 'ai-assistant',
        component: () => import('@/pages/dashboard/ai.vue'),
        meta: {
          requiresAuth: true,
          title: 'AI 业务助手',
          activeMenu: '/dashboard/ai',
          permission: PERMISSIONS.ai.assistantUse,
        },
      },
      {
        path: 'ai/provider-configs',
        name: 'ai-provider-configs',
        component: () => import('@/pages/dashboard/ai/provider-configs.vue'),
        meta: {
          requiresAuth: true,
          title: 'AI 模型配置',
          activeMenu: '/dashboard/ai',
          permission: PERMISSIONS.ai.providerConfigView,
        },
      },
      {
        path: 'user',
        name: 'user',
        component: () => import('@/pages/dashboard/user.vue'),
        meta: {
          requiresAuth: true,
          title: '用户管理',
          activeMenu: '/dashboard/user',
          permission: PERMISSIONS.user.list,
          allowDuringRecoveryBootstrap: true,
        },
      },
      {
        path: 'user/:id',
        name: 'user-detail',
        component: () => import('@/pages/dashboard/user/[id].vue'),
        meta: {
          requiresAuth: true,
          title: '用户详情',
          activeMenu: '/dashboard/user',
          permission: PERMISSIONS.user.view,
        },
      },
      {
        path: 'organization',
        name: 'organization',
        component: () => import('@/pages/dashboard/organization.vue'),
        meta: {
          requiresAuth: true,
          title: '组织架构',
          activeMenu: '/dashboard/organization',
          permission: PERMISSIONS.organization.list,
        },
      },
      {
        path: 'role',
        name: 'role-management',
        component: () => import('@/pages/dashboard/role.vue'),
        meta: {
          requiresAuth: true,
          title: '角色管理',
          activeMenu: '/dashboard/role',
          permission: PERMISSIONS.role.list,
        },
      },
      {
        path: 'permission',
        name: 'permission-catalog',
        component: () => import('@/pages/dashboard/permission.vue'),
        meta: {
          requiresAuth: true,
          title: '权限目录',
          activeMenu: '/dashboard/permission',
          permission: PERMISSIONS.permission.list,
        },
      },
      {
        path: 'activity',
        name: 'activity',
        component: () => import('@/pages/dashboard/activity/index.vue'),
        meta: {
          requiresAuth: true,
          title: '市场活动',
          activeMenu: '/dashboard/activity',
          permission: PERMISSIONS.activity.list,
        },
      },
      {
        path: 'activity/:id',
        name: 'activity-detail',
        component: () => import('@/pages/dashboard/activity/[id].vue'),
        meta: {
          requiresAuth: true,
          title: '市场活动详情',
          activeMenu: '/dashboard/activity',
          permission: PERMISSIONS.activity.view,
        },
      },
      {
        path: 'clue',
        name: 'clue',
        component: () => import('@/pages/dashboard/clue/index.vue'),
        meta: {
          requiresAuth: true,
          title: '线索管理',
          activeMenu: '/dashboard/clue',
          permission: PERMISSIONS.clue.list,
        },
      },
      {
        path: 'clue/detail/:id',
        name: 'clue-detail',
        component: () => import('@/pages/dashboard/clue/detail/[id].vue'),
        meta: {
          requiresAuth: true,
          title: '线索详情',
          activeMenu: '/dashboard/clue',
          permission: PERMISSIONS.clue.view,
        },
      },
      {
        path: 'customer',
        name: 'customer',
        component: () => import('@/pages/dashboard/customer.vue'),
        meta: {
          requiresAuth: true,
          title: '客户管理',
          activeMenu: '/dashboard/customer',
          permission: PERMISSIONS.customer.list,
        },
      },
      {
        path: 'customer/:id',
        name: 'customer-detail',
        component: () => import('@/pages/dashboard/customer/[id].vue'),
        meta: {
          requiresAuth: true,
          title: '客户详情',
          activeMenu: '/dashboard/customer',
          permission: PERMISSIONS.customer.view,
        },
      },
      {
        path: 'product',
        name: 'product',
        component: () => import('@/pages/dashboard/product/index.vue'),
        meta: {
          requiresAuth: true,
          title: '产品列表',
          activeMenu: '/dashboard/product',
          permission: PERMISSIONS.product.list,
        },
      },
      {
        path: 'product/category',
        name: 'product-category',
        component: () => import('@/pages/dashboard/product/category.vue'),
        meta: {
          requiresAuth: true,
          title: '产品分类',
          activeMenu: '/dashboard/product/category',
          permission: PERMISSIONS.product.category.list,
        },
      },
      {
        path: 'product/promotion',
        name: 'product-promotion',
        component: () => import('@/pages/dashboard/product/promotion.vue'),
        meta: {
          requiresAuth: true,
          title: '促销管理',
          activeMenu: '/dashboard/product/promotion',
          permission: PERMISSIONS.product.promotion.list,
        },
      },
      {
        path: 'product/stock',
        name: 'product-stock',
        component: () => import('@/pages/dashboard/product/stock.vue'),
        meta: {
          requiresAuth: true,
          title: '库存管理',
          activeMenu: '/dashboard/product/stock',
          permission: PERMISSIONS.product.stock.view,
        },
      },
      {
        path: 'opportunity',
        name: 'opportunity',
        component: () => import('@/pages/dashboard/opportunity.vue'),
        meta: {
          requiresAuth: true,
          title: '商机管理',
          activeMenu: '/dashboard/opportunity',
          permission: PERMISSIONS.opportunity.list,
        },
      },
      {
        path: 'test-drive',
        name: 'test-drive',
        component: () => import('@/pages/dashboard/test-drive.vue'),
        meta: {
          requiresAuth: true,
          title: '试驾管理',
          activeMenu: '/dashboard/test-drive',
          permission: PERMISSIONS.testDrive.list,
        },
      },
      {
        path: 'follow',
        name: 'follow',
        component: () => import('@/pages/dashboard/follow.vue'),
        meta: {
          requiresAuth: true,
          title: '跟进任务',
          activeMenu: '/dashboard/follow',
          permission: PERMISSIONS.followTask.list,
        },
      },
      {
        path: 'quote',
        name: 'quote',
        component: () => import('@/pages/dashboard/quote.vue'),
        meta: {
          requiresAuth: true,
          title: '报价订单',
          activeMenu: '/dashboard/quote',
          permission: PERMISSIONS.quote.list,
        },
      },
      {
        path: 'delivery',
        name: 'delivery',
        component: () => import('@/pages/dashboard/delivery.vue'),
        meta: {
          requiresAuth: true,
          title: '交付管理',
          activeMenu: '/dashboard/delivery',
          permission: PERMISSIONS.delivery.list,
        },
      },
      {
        path: 'tran',
        name: 'tran',
        component: () => import('@/pages/dashboard/tran/index.vue'),
        meta: {
          requiresAuth: true,
          title: '交易管理',
          activeMenu: '/dashboard/tran',
          permission: PERMISSIONS.tran.list,
        },
      },
      {
        path: 'tran/:id',
        name: 'tran-detail',
        component: () => import('@/pages/dashboard/tran/[id].vue'),
        meta: {
          requiresAuth: true,
          title: '交易详情',
          activeMenu: '/dashboard/tran',
          permission: PERMISSIONS.tran.view,
        },
      },
      {
        path: 'tran/approve/:id',
        name: 'tran-approve',
        component: () => import('@/pages/dashboard/tran/approve/[id].vue'),
        meta: {
          requiresAuth: true,
          title: '交易审批',
          activeMenu: '/dashboard/tran',
          permission: PERMISSIONS.tran.approve,
        },
      },
      {
        path: 'tran/invoice/:id',
        name: 'tran-invoice',
        component: () => import('@/pages/dashboard/tran/invoice/[id].vue'),
        meta: {
          requiresAuth: true,
          title: '交易发票',
          activeMenu: '/dashboard/tran',
          permission: PERMISSIONS.tran.invoice,
        },
      },
      {
        path: 'dict/type',
        name: 'dict-type',
        component: () => import('@/pages/dashboard/dict/type.vue'),
        meta: {
          requiresAuth: true,
          title: '字典管理',
          activeMenu: '/dashboard/dict/type',
          permission: PERMISSIONS.dict.type.list,
        },
      },
      {
        path: 'dict/value',
        name: 'dict-value',
        component: () => import('@/pages/dashboard/dict/value.vue'),
        meta: {
          requiresAuth: true,
          title: '字典管理',
          activeMenu: '/dashboard/dict/type',
          permission: PERMISSIONS.dict.value.list,
        },
      },
      {
        path: 'audit/login',
        name: 'audit-login',
        component: () => import('@/pages/dashboard/audit/login.vue'),
        meta: {
          requiresAuth: true,
          title: '登录记录',
          activeMenu: '/dashboard/audit/login',
          permission: PERMISSIONS.audit.login.list,
        },
      },
      {
        path: 'audit/operation',
        name: 'audit-operation',
        component: () => import('@/pages/dashboard/audit/operation.vue'),
        meta: {
          requiresAuth: true,
          title: '操作记录',
          activeMenu: '/dashboard/audit/operation',
          permission: PERMISSIONS.audit.operation.list,
        },
      },
    ],
  },
  {
    path: '/403',
    name: 'forbidden',
    component: () => import('@/pages/403.vue'),
    meta: { requiresAuth: true, title: '无权访问' },
  },
  {
    path: '/:pathMatch(.*)*',
    redirect: '/dashboard',
    meta: { requiresAuth: false },
  },
]
