export const PERMISSIONS = {
  activity: {
    list: 'activity:list',
    view: 'activity:view',
    add: 'activity:add',
    edit: 'activity:edit',
    delete: 'activity:delete',
  },
  clue: {
    list: 'clue:list',
    view: 'clue:view',
    add: 'clue:add',
    edit: 'clue:edit',
    delete: 'clue:delete',
    import: 'clue:import',
  },
  customer: {
    list: 'customer:list',
    view: 'customer:view',
    export: 'customer:export',
    transfer: 'customer:transfer',
  },
  tran: {
    list: 'tran:list',
    view: 'tran:view',
    create: 'tran:create',
    edit: 'tran:edit',
    delete: 'tran:delete',
    settle: 'tran:settle',
    resubmit: 'tran:resubmit',
    approve: 'tran:approve',
    invoice: 'tran:invoice',
    payment: 'tran:payment',
    refund: 'tran:refund',
  },
  product: {
    list: 'product:list',
    view: 'product:view',
    add: 'product:add',
    edit: 'product:edit',
    delete: 'product:delete',
    category: {
      list: 'product:category:list',
      view: 'product:category:view',
      add: 'product:category:add',
      edit: 'product:category:edit',
      delete: 'product:category:delete',
    },
    promotion: {
      list: 'product:promotion:list',
      view: 'product:promotion:view',
      add: 'product:promotion:add',
      edit: 'product:promotion:edit',
      delete: 'product:promotion:delete',
    },
    stock: {
      view: 'product:stock:view',
      adjust: 'product:stock:adjust',
    },
  },
  dict: {
    type: {
      list: 'dict:type:list',
      view: 'dict:type:view',
      add: 'dict:type:add',
      edit: 'dict:type:edit',
      delete: 'dict:type:delete',
    },
    value: {
      list: 'dict:value:list',
      view: 'dict:value:view',
      add: 'dict:value:add',
      edit: 'dict:value:edit',
      delete: 'dict:value:delete',
    },
    refresh: 'dict:cache:refresh',
  },
  user: {
    list: 'user:list',
    view: 'user:view',
    add: 'user:add',
    edit: 'user:edit',
    delete: 'user:delete',
    status: 'user:status',
    role: 'user:role',
    password: 'user:password',
  },
  statistic: {
    view: 'statistic:view',
  },
} as const
