export const PERMISSIONS = {
  activity: {
    list: 'activity:list',
    view: 'activity:view',
    add: 'activity:add',
    edit: 'activity:edit',
    delete: 'activity:delete',
  },
  clue: {
    list: 'clue:list',
    view: 'clue:view',
    add: 'clue:add',
    edit: 'clue:edit',
    delete: 'clue:delete',
    import: 'clue:import',
    transfer: 'clue:transfer',
    close: 'clue:close',
    restore: 'clue:restore',
  },
  customer: {
    list: 'customer:list',
    view: 'customer:view',
    export: 'customer:export',
    transfer: 'customer:transfer',
    merge: 'customer:merge',
    delete: 'customer:delete',
    sensitiveView: 'customer:sensitive:view',
  },
  tran: {
    list: 'tran:list',
    view: 'tran:view',
    create: 'tran:create',
    edit: 'tran:edit',
    delete: 'tran:delete',
    cancel: 'tran:cancel',
    close: 'tran:close',
    settle: 'tran:settle',
    resubmit: 'tran:resubmit',
    approve: 'tran:approve',
    invoice: 'tran:invoice',
    invoiceSensitive: 'tran:invoice:sensitive',
    payment: 'tran:payment',
    paymentConfirm: 'tran:payment:confirm',
    refund: 'tran:refund',
    refundApprove: 'tran:refund:approve',
    refundExecute: 'tran:refund:execute',
  },
  quote: {
    list: 'quote:list',
    view: 'quote:view',
    create: 'quote:create',
    edit: 'quote:edit',
    approve: 'quote:approve',
    confirm: 'quote:confirm',
    order: 'quote:order',
    cancel: 'quote:cancel',
  },
  delivery: {
    list: 'delivery:list',
    view: 'delivery:view',
    create: 'delivery:create',
    check: 'delivery:check',
    sign: 'delivery:sign',
    exception: 'delivery:exception',
    cancel: 'delivery:cancel',
  },
  product: {
    list: 'product:list',
    view: 'product:view',
    add: 'product:add',
    edit: 'product:edit',
    delete: 'product:delete',
    category: {
      list: 'product:category:list',
      view: 'product:category:view',
      add: 'product:category:add',
      edit: 'product:category:edit',
      delete: 'product:category:delete',
    },
    promotion: {
      list: 'product:promotion:list',
      view: 'product:promotion:view',
      add: 'product:promotion:add',
      edit: 'product:promotion:edit',
      delete: 'product:promotion:delete',
    },
    stock: {
      view: 'product:stock:view',
      adjust: 'product:stock:adjust',
    },
  },
  dict: {
    type: {
      list: 'dict:type:list',
      view: 'dict:type:view',
      add: 'dict:type:add',
      edit: 'dict:type:edit',
      delete: 'dict:type:delete',
    },
    value: {
      list: 'dict:value:list',
      view: 'dict:value:view',
      add: 'dict:value:add',
      edit: 'dict:value:edit',
      delete: 'dict:value:delete',
    },
    refresh: 'dict:cache:refresh',
  },
  user: {
    list: 'user:list',
    view: 'user:view',
    add: 'user:add',
    edit: 'user:edit',
    delete: 'user:delete',
    status: 'user:status',
    role: 'user:role',
    password: 'user:password',
  },
  statistic: {
    view: 'statistic:view',
  },
} as const
