package com.autodealer.crm.modules.identity.application.internal;

import com.autodealer.crm.modules.identity.application.api.model.TUser;
import com.autodealer.crm.modules.identity.persistence.mapper.TUserMapper;
import com.autodealer.crm.modules.identity.persistence.mapper.TUserSessionMapper;
import com.autodealer.crm.modules.identity.persistence.model.TUserSession;
import com.autodealer.crm.modules.identity.application.api.*;

import com.autodealer.crm.modules.audit.application.api.OperationAuditRecorder;
import com.autodealer.crm.modules.audit.application.api.AuditActionEnum;
import com.autodealer.crm.modules.identity.application.api.security.CurrentUserProvider;
import com.autodealer.crm.shared.infrastructure.cache.RedisKeys;
import com.autodealer.crm.modules.identity.application.api.dto.user.UserSessionDtos;
import com.autodealer.crm.shared.error.BusinessException;
import com.autodealer.crm.shared.infrastructure.cache.RedisManager;
import com.autodealer.crm.modules.identity.persistence.mapper.*;
import com.autodealer.crm.modules.identity.persistence.model.*;
import com.autodealer.crm.modules.identity.application.api.model.*;
import com.autodealer.crm.shared.error.CodeEnum;
import com.autodealer.crm.modules.identity.application.internal.UserAuthorizationPolicy;
import com.autodealer.crm.modules.identity.application.internal.UserSessionServiceImpl;
import com.autodealer.crm.modules.identity.domain.SessionTokenDigester;
import com.auth0.jwt.JWT;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.*;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;

import java.time.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class UserSessionServiceImplTest {
 @Mock TUserSessionMapper sessions;@Mock TUserMapper users;@Mock RedisManager redis;@Mock CurrentUserProvider current;@Mock UserAuthorizationPolicy policy;@Mock OperationAuditRecorder audit;
 Clock clock=Clock.fixed(Instant.parse("2026-07-12T03:00:00Z"),ZoneOffset.UTC);SessionTokenDigester digester;UserSessionServiceImpl service;
 @BeforeEach void setup(){digester=new SessionTokenDigester();service=new UserSessionServiceImpl(sessions,users,redis,digester,current,policy,audit,clock,14400,1800,604800,86400,300,2);lenient().when(users.selectByPrimaryKeyForUpdate(7)).thenAnswer(ignored->user());}
 @Test void createUsesOpaqueSessionAndStoresOnlyDigest(){TUser user=user();when(sessions.selectActiveByUserId(eq(7),any())).thenReturn(List.of());when(sessions.insert(any())).thenReturn(1);when(redis.set(anyString(),anyString(),anyLong())).thenReturn(true);when(redis.addToSet(anyString(),anyString(),anyLong())).thenReturn(true);when(users.incrementSessionRevision(7)).thenReturn(1);UserSessionDtos.Issued issued=service.create(user,false,request());ArgumentCaptor<TUserSession> c=ArgumentCaptor.forClass(TUserSession.class);verify(sessions).insert(c.capture());var decoded=JWT.decode(issued.token());assertEquals(43,issued.sessionId().length());assertEquals(issued.sessionId(),decoded.getClaim("sessionId").asString());assertEquals(7,decoded.getClaim("userId").asInt());assertTrue(decoded.getClaim("loginAct").isMissing());assertNotEquals(issued.token(),c.getValue().getTokenDigest());assertEquals(64,c.getValue().getTokenDigest().length());verify(audit).recordAuthenticatedActor(eq(AuditActionEnum.USER_SESSION_CREATE),eq("7"),eq("SUCCESS"),contains("LOGIN"),eq(7),isNull());}
 @Test void sessionCreateAuditFailureTriggersRegisteredRedisRollbackCleanup(){when(sessions.selectActiveByUserId(eq(7),any())).thenReturn(List.of());when(sessions.insert(any())).thenReturn(1);when(redis.set(anyString(),anyString(),anyLong())).thenReturn(true);when(redis.addToSet(anyString(),anyString(),anyLong())).thenReturn(true);when(users.incrementSessionRevision(7)).thenReturn(1);doThrow(new IllegalStateException("audit failed")).when(audit).recordAuthenticatedActor(eq(AuditActionEnum.USER_SESSION_CREATE),eq("7"),eq("SUCCESS"),anyString(),eq(7),isNull());TransactionSynchronizationManager.initSynchronization();try{assertThrows(IllegalStateException.class,()->service.create(user(),false,request()));for(TransactionSynchronization synchronization:TransactionSynchronizationManager.getSynchronizations())synchronization.afterCompletion(TransactionSynchronization.STATUS_ROLLED_BACK);verify(redis).delete(argThat(key->key.startsWith("cdrm:session:")));verify(redis).removeFromSet(eq(RedisKeys.userSessionIndex(7)),anyString());}finally{TransactionSynchronizationManager.clearSynchronization();}}
 @Test void redisWriteFailureDoesNotReturnSession(){when(sessions.selectActiveByUserId(eq(7),any())).thenReturn(List.of());when(sessions.insert(any())).thenReturn(1);when(redis.set(anyString(),anyString(),anyLong())).thenReturn(false);BusinessException e=assertThrows(BusinessException.class,()->service.create(user(),false,request()));assertEquals(CodeEnum.SESSION_CACHE_FAILED,e.getCodeEnum());verify(users,never()).incrementSessionRevision(anyInt());}
 @Test void maximumConcurrencyRevokesDeterministicOldest(){TUserSession newer=fact("newer",LocalDateTime.of(2026,7,12,2,0));TUserSession oldest=fact("oldest",LocalDateTime.of(2026,7,11,2,0));when(sessions.selectActiveByUserId(eq(7),any())).thenReturn(new ArrayList<>(List.of(newer,oldest)));when(sessions.revokeOne(eq("oldest"),eq(7),any(),eq(7),anyString(),eq("MAX_CONCURRENT"))).thenReturn(1);when(redis.delete(anyString())).thenReturn(true);when(redis.removeFromSet(anyString(),eq("oldest"))).thenReturn(true);when(sessions.insert(any())).thenReturn(1);when(redis.set(anyString(),anyString(),anyLong())).thenReturn(true);when(redis.addToSet(anyString(),anyString(),anyLong())).thenReturn(true);when(users.incrementSessionRevision(7)).thenReturn(1);service.create(user(),false,request());InOrder order=inOrder(users,sessions);order.verify(users).selectByPrimaryKeyForUpdate(7);order.verify(sessions).selectActiveByUserId(eq(7),any());verify(sessions).revokeOne(eq("oldest"),eq(7),any(),eq(7),anyString(),eq("MAX_CONCURRENT"));verify(sessions,never()).revokeOne(eq("newer"),anyInt(),any(),any(),anyString(),anyString());}
 @Test void validateChecksDigestIdleAbsoluteAndThrottlesTouch(){String raw="signed-token";TUserSession fact=fact("sid",LocalDateTime.of(2026,7,12,2,0));fact.setTokenDigest(digester.digest(raw));fact.setUserId(7);fact.setIssuedAuthVersion(3L);fact.setLastActivityTime(LocalDateTime.of(2026,7,12,2,59));fact.setIdleExpiresAt(LocalDateTime.of(2026,7,12,3,30));fact.setAbsoluteExpiresAt(LocalDateTime.of(2026,7,12,7,0));when(redis.get(anyString())).thenReturn(fact.getTokenDigest());when(sessions.selectBySessionId("sid")).thenReturn(fact);assertTrue(service.validateAndTouch(raw,7,"sid",3L));verify(sessions,never()).touchBySessionIdAndVersion(anyString(),anyInt(),any(),any());fact.setLastActivityTime(LocalDateTime.of(2026,7,12,2,0));when(sessions.touchBySessionIdAndVersion(eq("sid"),eq(0),any(),any())).thenReturn(1);when(redis.expire(anyString(),anyLong())).thenReturn(true);assertTrue(service.validateAndTouch(raw,7,"sid",3L));verify(redis).expire(anyString(),longThat(v->v>0&&v<=1800));}
 @Test void absoluteOrIdleExpiryFailsClosed(){String raw="signed";TUserSession fact=fact("sid",LocalDateTime.of(2026,7,12,2,0));fact.setTokenDigest(digester.digest(raw));fact.setUserId(7);fact.setIssuedAuthVersion(3L);fact.setIdleExpiresAt(LocalDateTime.of(2026,7,12,3,0));fact.setAbsoluteExpiresAt(LocalDateTime.of(2026,7,12,4,0));when(redis.get(anyString())).thenReturn(fact.getTokenDigest());when(sessions.selectBySessionId("sid")).thenReturn(fact);assertFalse(service.validateAndTouch(raw,7,"sid",3L));}
 @Test void explicitRevocationRedisFalseReturnsFailureAfterDatabaseFact(){TUserSession fact=fact("sid",LocalDateTime.of(2026,7,12,2,0));fact.setUserId(7);when(current.getCurrentUserId()).thenReturn(7);when(sessions.selectBySessionId("sid")).thenReturn(fact);when(users.incrementSessionRevisionByExpected(7,4L)).thenReturn(1);when(sessions.revokeOne(eq("sid"),eq(7),any(),eq(7),anyString(),eq("SELF_ONE"))).thenReturn(1);when(redis.delete(anyString())).thenReturn(false);UserSessionDtos.RevokeRequest q=new UserSessionDtos.RevokeRequest();q.setSessionRevision(4L);q.setReason("设备遗失");BusinessException e=assertThrows(BusinessException.class,()->service.revokeOwn("sid",q));assertEquals(CodeEnum.SESSION_CACHE_FAILED,e.getCodeEnum());verify(sessions).revokeOne(eq("sid"),eq(7),any(),eq(7),eq("设备遗失"),eq("SELF_ONE"));}
 @Test void managedListReusesObjectManagementBoundary(){TUser target=user();target.setId(9);target.setSessionRevision(2L);when(users.selectByPrimaryKey(9)).thenReturn(target);when(sessions.selectActiveByUserId(eq(9),any())).thenReturn(List.of());service.managedSessions(9);verify(policy).requireManage(target);}
 @Test void legacyOnlyRevokeAllDeletesLegacyKey(){when(current.getCurrentUserId()).thenReturn(7);when(current.getCurrentSessionId()).thenReturn(null);when(sessions.selectAllActiveSessionIdsByUserId(eq(7),any())).thenReturn(List.of());when(redis.keyPresence(RedisKeys.userLogin(7))).thenReturn(RedisManager.KeyPresence.PRESENT,RedisManager.KeyPresence.ABSENT);when(users.incrementSessionRevisionByExpected(7,4L)).thenReturn(1);when(redis.delete(RedisKeys.userLogin(7))).thenReturn(true);when(users.selectByPrimaryKey(7)).thenReturn(user());when(sessions.selectActiveByUserId(eq(7),any())).thenReturn(List.of());service.revokeOwnAll(request(4L));verify(redis).delete(RedisKeys.userLogin(7));verify(sessions,never()).revokeAll(anyInt(),any(),any(),anyString(),anyString());}
 @Test void legacyDeleteFalseReturnsSessionCacheFailure(){when(current.getCurrentUserId()).thenReturn(7);when(sessions.selectAllActiveSessionIdsByUserId(eq(7),any())).thenReturn(List.of());when(redis.keyPresence(RedisKeys.userLogin(7))).thenReturn(RedisManager.KeyPresence.PRESENT);when(users.incrementSessionRevisionByExpected(7,4L)).thenReturn(1);when(redis.delete(RedisKeys.userLogin(7))).thenReturn(false);BusinessException error=assertThrows(BusinessException.class,()->service.revokeOwnAll(request(4L)));assertEquals(CodeEnum.SESSION_CACHE_FAILED,error.getCodeEnum());}
 @Test void legacyCurrentRevokeOthersRevokesAllNewFactsButKeepsLegacyCurrent(){when(current.getCurrentUserId()).thenReturn(7);when(current.getCurrentSessionId()).thenReturn(null);when(sessions.selectAllActiveSessionIdsByUserId(eq(7),any())).thenReturn(List.of("new-session"));when(users.incrementSessionRevisionByExpected(7,4L)).thenReturn(1);when(sessions.revokeAll(eq(7),any(),eq(7),anyString(),eq("SELF_OTHERS"))).thenReturn(1);when(redis.delete(RedisKeys.userSession("new-session"))).thenReturn(true);when(redis.removeFromSet(RedisKeys.userSessionIndex(7),"new-session")).thenReturn(true);when(users.selectByPrimaryKey(7)).thenReturn(user());when(sessions.selectActiveByUserId(eq(7),any())).thenReturn(List.of());service.revokeOwnOthers(request(4L));verify(sessions).revokeAll(eq(7),any(),eq(7),anyString(),eq("SELF_OTHERS"));verify(redis,never()).delete(RedisKeys.userLogin(7));}
 @Test void newCurrentRevokeOthersDeletesMixedLegacySession(){when(current.getCurrentUserId()).thenReturn(7);when(current.getCurrentSessionId()).thenReturn("current");when(sessions.selectAllActiveSessionIdsByUserId(eq(7),any())).thenReturn(List.of("current"));when(redis.keyPresence(RedisKeys.userLogin(7))).thenReturn(RedisManager.KeyPresence.PRESENT,RedisManager.KeyPresence.ABSENT);when(users.incrementSessionRevisionByExpected(7,4L)).thenReturn(1);when(redis.delete(RedisKeys.userLogin(7))).thenReturn(true);when(users.selectByPrimaryKey(7)).thenReturn(user());when(sessions.selectActiveByUserId(eq(7),any())).thenReturn(List.of(fact("current",LocalDateTime.of(2026,7,12,2,0))));service.revokeOwnOthers(request(4L));verify(redis).delete(RedisKeys.userLogin(7));verify(sessions,never()).revokeOthers(anyInt(),anyString(),any(),any(),anyString(),anyString());}
 @Test void managedAllowedActionsReflectCallerMutationPermission(){TUser target=user();target.setId(9);target.setSessionRevision(2L);TUserSession active=fact("managed",LocalDateTime.of(2026,7,12,2,0));active.setUserId(9);when(users.selectByPrimaryKey(9)).thenReturn(target);when(sessions.selectActiveByUserId(eq(9),any())).thenReturn(List.of(active));when(current.hasAuthority(anyString())).thenReturn(false,true);UserSessionDtos.Collection readOnly=service.managedSessions(9);UserSessionDtos.Collection writable=service.managedSessions(9);assertTrue(readOnly.getAllowedActions().isEmpty());assertEquals("缺少用户状态管理权限",readOnly.getUnavailableReasons().get("REVOKE_ALL"));assertTrue(readOnly.getSessions().get(0).getAllowedActions().isEmpty());assertEquals("缺少用户状态管理权限",readOnly.getSessions().get(0).getUnavailableReasons().get("REVOKE"));assertEquals(List.of("REVOKE_ALL"),writable.getAllowedActions());assertEquals(List.of("REVOKE"),writable.getSessions().get(0).getAllowedActions());}
 @Test void expiredSpecifiedSessionReturnsStableGoneError(){TUserSession expired=fact("expired",LocalDateTime.of(2026,7,12,2,0));expired.setIdleExpiresAt(LocalDateTime.of(2026,7,12,3,0));when(current.getCurrentUserId()).thenReturn(7);when(sessions.selectBySessionId("expired")).thenReturn(expired);BusinessException error=assertThrows(BusinessException.class,()->service.revokeOwn("expired",request(4L)));assertEquals(CodeEnum.SESSION_EXPIRED,error.getCodeEnum());verify(users,never()).incrementSessionRevisionByExpected(anyInt(),anyLong());}
 private TUser user(){TUser u=new TUser();u.setId(7);u.setLoginAct("changed-login-not-in-jwt");u.setAuthVersion(3L);u.setSessionRevision(0L);return u;}
 private TUserSession fact(String sid,LocalDateTime login){TUserSession s=new TUserSession();s.setSessionId(sid);s.setUserId(7);s.setRememberMe(false);s.setLoginTime(login);s.setLastActivityTime(login);s.setIdleExpiresAt(LocalDateTime.of(2026,7,12,3,30));s.setAbsoluteExpiresAt(LocalDateTime.of(2026,7,12,7,0));s.setVersion(0);return s;}
 private UserSessionDtos.RevokeRequest request(long revision){UserSessionDtos.RevokeRequest request=new UserSessionDtos.RevokeRequest();request.setSessionRevision(revision);request.setReason("安全处置");return request;}
 private MockHttpServletRequest request(){MockHttpServletRequest r=new MockHttpServletRequest();r.addHeader("User-Agent","Mozilla/5.0 Chrome/120.0");r.setRemoteAddr("192.168.12.55");return r;}
}
