package com.autodealer.crm.service;

import com.autodealer.crm.audit.AuditActionEnum;
import com.autodealer.crm.audit.OperationAuditRecorder;
import com.autodealer.crm.audit.SecurityFailureAuditService;
import com.autodealer.crm.config.security.CurrentUserProvider;
import com.autodealer.crm.dto.credential.CredentialDtos.*;
import com.autodealer.crm.enums.*;
import com.autodealer.crm.exception.BusinessException;
import com.autodealer.crm.manager.RedisManager;
import com.autodealer.crm.mapper.*;
import com.autodealer.crm.model.*;
import com.autodealer.crm.result.CodeEnum;
import com.autodealer.crm.service.impl.CredentialServiceImpl;
import com.autodealer.crm.service.impl.CredentialDerivationCodec;
import com.autodealer.crm.service.impl.CredentialIssuanceService;
import com.autodealer.crm.service.impl.CredentialTokenDigester;
import com.autodealer.crm.service.impl.UserAuthorizationPolicy;
import com.autodealer.crm.service.impl.UserSecurityMutationCoordinator;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.*;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.util.ReflectionTestUtils;
import java.time.LocalDateTime;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class CredentialServiceImplTest {
 @Mock TUserMapper users;@Mock TAccountCredentialMapper credentials;@Mock TPasswordHistoryMapper history;@Mock TEmployeeMapper employees;@Mock PasswordEncoder encoder;
 @Mock CurrentUserProvider current;@Mock UserAuthorizationPolicy policy;@Mock RedisManager redis;@Mock OperationAuditRecorder audit;@Mock SecurityFailureAuditService failureAudit;@Mock UserSecurityMutationCoordinator securityMutations;@Mock CredentialDeliveryPort port;@Mock CredentialIssuanceService issuance;@Mock TAuthorizationGraphLockMapper graphLocks;
 private CredentialDerivationCodec codec;private CredentialTokenDigester tokenDigester;private CredentialServiceImpl service;
 @BeforeEach void setup(){codec=spy(new CredentialDerivationCodec("test-only-credential-derivation-key-00000001"));tokenDigester=spy(new CredentialTokenDigester("test-secret-key-for-unit-tests-only-2024"));lenient().when(port.validateTarget(any(),any())).thenReturn(new CredentialDeliveryPort.DeliveryStatus("QUEUED"));lenient().when(graphLocks.lockByName(anyString())).thenAnswer(invocation->invocation.getArgument(0));TEmployee employee=new TEmployee();employee.setUserId(8);employee.setEmploymentStatus(EmployeeStatus.ACTIVE);lenient().when(employees.selectByUserId(8)).thenReturn(employee);lenient().when(employees.selectByUserIdForUpdate(8)).thenReturn(employee);service=new CredentialServiceImpl(users,credentials,history,employees,encoder,port,current,policy,redis,audit,securityMutations,issuance,codec,tokenDigester,failureAudit,graphLocks);}
 @Test void forgotHasSameShapeWhenAccountDoesNotExist(){when(users.selectByLoginAct("missing")).thenReturn(null);RequestAccepted result=service.forgot(forgot("missing"));assertTrue(result.accepted());assertEquals("QUEUED",result.deliveryStatus());verifyNoInteractions(credentials);}
 @Test void forgotDoesNotDeliverToUnverifiedContact(){TUser user=user(8);user.setAccountStatus(AccountStatus.ACTIVE);TEmployee employee=new TEmployee();employee.setPhone("13800000001");employee.setPhoneVerified(false);when(users.selectByLoginAct("u8")).thenReturn(user);when(employees.selectByUserId(8)).thenReturn(employee);RequestAccepted result=service.forgot(forgot("u8"));assertTrue(result.accepted());verifyNoInteractions(issuance);verify(port,never()).deliver(any());}
 @Test void forgotCooldownDoesNotIssueOrDeliverAgain(){TUser user=user(8);user.setAccountStatus(AccountStatus.ACTIVE);TEmployee employee=new TEmployee();employee.setEmail("u8@example.com");employee.setEmailVerified(true);when(users.selectByLoginAct("u8")).thenReturn(user);when(employees.selectByUserId(8)).thenReturn(employee);doThrow(new BusinessException(CodeEnum.CREDENTIAL_RATE_LIMITED,"冷却中")).when(issuance).enqueue(anyInt(),any(),anyString(),anyString(),anyString(),any(),any(),any(),anyString(),any(),any(),any(),any(),any());RequestAccepted result=service.forgot(forgot("u8"));assertEquals("QUEUED",result.deliveryStatus());verify(issuance).enqueue(anyInt(),eq(CredentialPurpose.SELF_RESET),anyString(),anyString(),anyString(),any(),any(),any(),anyString(),any(),any(),any(),any(),eq(java.time.Duration.ofMinutes(5)));verify(port,never()).deliver(any());}
 @Test void forgotRateLimitKeepsPublicResponseShapeAndDoesNotLookupAccount(){ReflectionTestUtils.setField(service,"credentialRateLimitEnabled",true);when(redis.incrementSlidingWindow(anyString(),eq(900L))).thenReturn(6L,1L);RequestAccepted result=service.forgot(forgot("u8"));assertTrue(result.accepted());assertEquals("QUEUED",result.deliveryStatus());verify(users,never()).selectByLoginAct(anyString());verify(failureAudit).recordAnonymous(eq(AuditActionEnum.USER_CREDENTIAL_RATE_LIMIT),anyString(),contains("FORGOT"));}
 @Test void forgotHasSameShapeWhenOutboxTransactionFails(){TUser user=user(8);user.setAccountStatus(AccountStatus.ACTIVE);TEmployee employee=new TEmployee();employee.setPhone("13800000001");employee.setPhoneVerified(true);when(users.selectByLoginAct("u8")).thenReturn(user);when(employees.selectByUserId(8)).thenReturn(employee);doThrow(new IllegalStateException("outbox unavailable")).when(issuance).enqueue(anyInt(),any(),anyString(),anyString(),anyString(),any(),any(),any(),anyString(),any(),any(),any(),any(),any());RequestAccepted result=service.forgot(forgot("u8"));assertTrue(result.accepted());assertEquals("QUEUED",result.deliveryStatus());verify(port,never()).deliver(any());}
 @Test void persistedIssuanceContainsOnlyCommitmentNonceAndQueuedMessageWithoutDerivingRaw(){
     TUser user=user(8);user.setPhone("13900000009");TEmployee employee=new TEmployee();employee.setUserId(8);
     employee.setEmploymentStatus(EmployeeStatus.ACTIVE);employee.setPhone("13800000001");
     when(users.selectByPrimaryKey(8)).thenReturn(user);when(employees.selectByUserId(8)).thenReturn(employee);
     when(current.getCurrentUserId()).thenReturn(1);
     ArgumentCaptor<String> commitment=ArgumentCaptor.forClass(String.class);
     ArgumentCaptor<String> messageId=ArgumentCaptor.forClass(String.class);
     ArgumentCaptor<String> nonce=ArgumentCaptor.forClass(String.class);

     ManagedDeliveryResult result=service.issueInvitation(8,"invite");

     assertEquals("QUEUED",result.deliveryStatus());
     verify(issuance).enqueue(eq(8),eq(CredentialPurpose.INVITATION),commitment.capture(),messageId.capture(),nonce.capture(),
             anyString(),isNull(),eq(1),eq("invite"),isNull(),isNull(),any(),any(),eq(java.time.Duration.ofMinutes(5)));
     assertTrue(commitment.getValue().matches("[0-9a-f]{64}"));
     assertEquals(codec.deliveryCommitment(messageId.getValue(),CredentialPurpose.INVITATION,nonce.getValue()),commitment.getValue());
     verify(codec,never()).derive(anyString(),any(),anyString());verify(port,never()).deliver(any());
 }
 @Test void managedIssueRejectsWhenChannelIsMissingBeforeOutboxWrite(){TUser user=user(8);user.setPhone("13800000001");when(users.selectByPrimaryKey(8)).thenReturn(user);when(current.getCurrentUserId()).thenReturn(1);when(port.validateTarget(any(),any())).thenReturn(new CredentialDeliveryPort.DeliveryStatus("CHANNEL_NOT_CONFIGURED"));BusinessException exception=assertThrows(BusinessException.class,()->service.issueInvitation(8,"invite"));assertEquals(CodeEnum.CREDENTIAL_DELIVERY_FAILED,exception.getCodeEnum());verifyNoInteractions(issuance);}
 @Test void managedIssueRejectsWithoutDeliveryContactBeforeOutboxWrite(){TUser user=user(8);when(users.selectByPrimaryKey(8)).thenReturn(user);when(current.getCurrentUserId()).thenReturn(1);when(port.validateTarget(any(),any())).thenReturn(new CredentialDeliveryPort.DeliveryStatus("NO_DELIVERY_CONTACT"));BusinessException exception=assertThrows(BusinessException.class,()->service.issueInvitation(8,"invite"));assertEquals(CodeEnum.CREDENTIAL_DELIVERY_FAILED,exception.getCodeEnum());verifyNoInteractions(issuance);}
 @Test void activationAttemptLimitFailsBeforeCredentialLookup(){ReflectionTestUtils.setField(service,"credentialRateLimitEnabled",true);when(redis.incrementSlidingWindow(anyString(),eq(900L))).thenReturn(11L,1L);BusinessException ex=assertThrows(BusinessException.class,()->service.activate(activate("raw","Valid1A")));assertEquals(CodeEnum.CREDENTIAL_RATE_LIMITED,ex.getCodeEnum());verify(credentials,never()).selectByDigest(anyString());verify(failureAudit).recordAnonymous(eq(AuditActionEnum.USER_CREDENTIAL_RATE_LIMIT),anyString(),contains("ACTIVATE"));}
 @Test void invalidCredentialUsesSharedTokenDigesterAndWritesIndependentRejectedAudit(){String expected=new CredentialTokenDigester("test-secret-key-for-unit-tests-only-2024").digest("raw");when(credentials.selectByDigest(anyString())).thenReturn(null);BusinessException ex=assertThrows(BusinessException.class,()->service.activate(activate("raw","Valid1A")));assertEquals(CodeEnum.CREDENTIAL_INVALID,ex.getCodeEnum());verify(tokenDigester).digest("raw");verify(credentials).selectByDigest(expected);verify(failureAudit).recordAnonymous(eq(AuditActionEnum.USER_CREDENTIAL_ATTEMPT_REJECTED),matches("[0-9a-f]{16}"),contains("INVALID"));}
 @Test void forgotContactLimitKeepsSamePublicShape(){ReflectionTestUtils.setField(service,"credentialRateLimitEnabled",true);TUser user=user(8);user.setAccountStatus(AccountStatus.ACTIVE);TEmployee employee=new TEmployee();employee.setPhone("13800000001");employee.setPhoneVerified(true);when(users.selectByLoginAct("u8")).thenReturn(user);when(employees.selectByUserId(8)).thenReturn(employee);when(redis.incrementSlidingWindow(anyString(),eq(900L))).thenReturn(1L,1L,6L);RequestAccepted result=service.forgot(forgot("u8"));assertTrue(result.accepted());assertEquals("QUEUED",result.deliveryStatus());verifyNoInteractions(issuance);verify(failureAudit).recordAnonymous(eq(AuditActionEnum.USER_CREDENTIAL_RATE_LIMIT),anyString(),contains("FORGOT_CONTACT"));}
 @Test void outOfScopeManagerCannotConsumeTargetOrContactQuota(){ReflectionTestUtils.setField(service,"credentialRateLimitEnabled",true);when(redis.incrementSlidingWindow(anyString(),eq(3600L))).thenReturn(1L);TUser target=user(8);when(users.selectByPrimaryKey(8)).thenReturn(target);doThrow(new BusinessException(CodeEnum.ACCESS_DENIED)).when(policy).requireManage(target);ManagedRequest request=new ManagedRequest();request.setAccountVersion(0);request.setReason("越权尝试");BusinessException ex=assertThrows(BusinessException.class,()->service.reinvite(8,request));assertEquals(CodeEnum.ACCESS_DENIED,ex.getCodeEnum());verify(redis,times(1)).incrementSlidingWindow(anyString(),eq(3600L));verifyNoInteractions(issuance);}
 @Test void adminResetRejectsSameOrHigherAuthorizationBeforeTargetQuotaAndMutation(){ReflectionTestUtils.setField(service,"credentialRateLimitEnabled",true);when(redis.incrementSlidingWindow(anyString(),eq(3600L))).thenReturn(1L);TUser target=user(8);when(users.selectByPrimaryKey(8)).thenReturn(target);doThrow(new BusinessException(CodeEnum.ACCESS_DENIED)).when(policy).requireAuthorizationManage(target);ManagedRequest request=new ManagedRequest();request.setAccountVersion(0);request.setReason("同级不得重置");BusinessException ex=assertThrows(BusinessException.class,()->service.adminReset(8,request));assertEquals(CodeEnum.ACCESS_DENIED,ex.getCodeEnum());verify(policy).requireAuthorizationManage(target);verify(redis,times(1)).incrementSlidingWindow(anyString(),eq(3600L));verify(users,never()).updateMustChangePasswordByExpected(anyInt(),anyInt(),anyBoolean());verifyNoInteractions(issuance);}
 @Test void adminResetCannotInvalidateLastAvailableOrdinaryAdministrator(){TUser target=user(8);target.setAccountStatus(AccountStatus.ACTIVE);when(users.selectByPrimaryKey(8)).thenReturn(target);TRole adminRole=new TRole();adminRole.setRole("admin");when(users.selectRolesByUserId(8)).thenReturn(java.util.List.of(adminRole));when(users.countAvailableAdminUsersExcluding(8)).thenReturn(0);ManagedRequest request=new ManagedRequest();request.setAccountVersion(0);request.setReason("最后管理员保护");BusinessException ex=assertThrows(BusinessException.class,()->service.adminReset(8,request));assertEquals(CodeEnum.LAST_AVAILABLE_ADMIN_REQUIRED,ex.getCodeEnum());verify(users,never()).updateMustChangePasswordByExpected(anyInt(),anyInt(),anyBoolean());verifyNoInteractions(issuance);}
 @Test void managedChannelValidationExceptionUsesStable625(){TUser user=user(8);user.setPhone("13800000001");when(users.selectByPrimaryKey(8)).thenReturn(user);when(current.getCurrentUserId()).thenReturn(1);when(port.validateTarget(any(),any())).thenThrow(new IllegalStateException("channel"));BusinessException e=assertThrows(BusinessException.class,()->service.issueInvitation(8,"invite"));assertEquals(CodeEnum.CREDENTIAL_DELIVERY_FAILED,e.getCodeEnum());verifyNoInteractions(issuance);}
 @Test void concurrentSecondConsumptionFailsClosed(){TUser user=user(8);when(users.selectByPrimaryKeyForUpdate(8)).thenReturn(user);TAccountCredential first=credential(CredentialStatus.ISSUED,true);TAccountCredential latest=credential(CredentialStatus.CONSUMED,false);when(credentials.selectByDigest(anyString())).thenReturn(first,latest);when(credentials.consumeByIdAndVersion(eq(1L),eq(0),any())).thenReturn(0);BusinessException ex=assertThrows(BusinessException.class,()->service.activate(activate("raw","Valid1A")));assertEquals(CodeEnum.CREDENTIAL_ALREADY_USED,ex.getCodeEnum());verify(users,never()).activateCredentialState(anyInt(),anyInt(),anyString(),anyBoolean(),any());}
 @Test void invitationActivationMovesPendingEmployeeToActive(){TUser user=user(8);user.setLoginPwd("oldHash");TEmployee employee=new TEmployee();employee.setUserId(8);employee.setEmploymentStatus(EmployeeStatus.PENDING);when(users.selectByPrimaryKeyForUpdate(8)).thenReturn(user);when(employees.selectByUserIdForUpdate(8)).thenReturn(employee);when(credentials.selectByDigest(anyString())).thenReturn(credential(CredentialStatus.ISSUED,true));when(credentials.consumeByIdAndVersion(eq(1L),eq(0),any())).thenReturn(1);when(history.insert(any())).thenReturn(1);when(users.activateCredentialState(eq(8),eq(0),nullable(String.class),eq(true),any())).thenReturn(1);when(employees.activatePendingByUserId(eq(8),any())).thenReturn(1);service.activate(activate("raw","Valid1A"));verify(employees).activatePendingByUserId(eq(8),any());verify(securityMutations).accessChanged(8,null,"密码变化");}
 @Test void revokedEmploymentCannotConsumeOldResetCredential(){TUser user=user(8);user.setAccountStatus(AccountStatus.DISABLED);TEmployee employee=new TEmployee();employee.setUserId(8);employee.setEmploymentStatus(EmployeeStatus.LEFT);TAccountCredential reset=credential(CredentialStatus.ISSUED,true);reset.setPurpose(CredentialPurpose.ADMIN_RESET);when(users.selectByPrimaryKeyForUpdate(8)).thenReturn(user);when(employees.selectByUserIdForUpdate(8)).thenReturn(employee);when(credentials.selectByDigest(anyString())).thenReturn(reset);ResetRequest request=new ResetRequest();request.setCredential("raw");request.setNewPassword("Valid1A");BusinessException ex=assertThrows(BusinessException.class,()->service.reset(request));assertEquals(CodeEnum.USER_LIFECYCLE_CONFLICT,ex.getCodeEnum());verify(credentials,never()).consumeByIdAndVersion(anyLong(),anyInt(),any());verify(users,never()).updatePasswordCredentialState(anyInt(),anyInt(),anyString(),anyBoolean(),any());}
 @Test void phoneVerificationQueuesCredentialBoundToCurrentContactVersion(){TUser user=user(8);user.setAccountStatus(AccountStatus.ACTIVE);TEmployee employee=new TEmployee();employee.setId(18);employee.setUserId(8);employee.setPhone("13800000001");employee.setProfileVersion(4);employee.setEmploymentStatus(EmployeeStatus.ACTIVE);when(current.getCurrentUserId()).thenReturn(8);when(users.selectByPrimaryKeyForUpdate(8)).thenReturn(user);when(employees.selectByUserIdForUpdate(8)).thenReturn(employee);ContactVerificationRequest request=new ContactVerificationRequest();request.setChannel(ContactChannel.PHONE);service.requestContactVerification(request);verify(users).selectByPrimaryKeyForUpdate(8);verify(employees).selectByUserIdForUpdate(8);verify(issuance).enqueue(eq(8),eq(CredentialPurpose.PHONE_VERIFY),anyString(),anyString(),anyString(),anyString(),isNull(),eq(8),eq("CONTACT_VERIFICATION"),argThat(value->value!=null&&!value.equals("13800000001")),eq(4),any(),any(),eq(java.time.Duration.ofMinutes(5)));verify(port,never()).deliver(any());}
 @Test void verifyContactMarksOnlyTheContactAndProfileVersionBoundAtIssueTime(){TUser user=user(8);TEmployee employee=new TEmployee();employee.setId(18);employee.setUserId(8);employee.setProfileVersion(3);employee.setPhone("13800000001");employee.setEmploymentStatus(EmployeeStatus.ACTIVE);TAccountCredential token=contactCredential(3,"13800000001");when(credentials.selectByDigest(anyString())).thenReturn(token);when(users.selectByPrimaryKeyForUpdate(8)).thenReturn(user);when(employees.selectByUserIdForUpdate(8)).thenReturn(employee);when(credentials.consumeByIdAndVersion(eq(1L),eq(0),any())).thenReturn(1);when(employees.markContactVerifiedByProfileVersion(eq(18),eq(3),eq("PHONE"),any())).thenReturn(1);VerifyContactRequest request=new VerifyContactRequest();request.setCredential("raw");service.verifyContact(request);verify(employees).markContactVerifiedByProfileVersion(eq(18),eq(3),eq("PHONE"),any());}
 @Test void verifyContactRejectsAChangedProfileBeforeConsumingCredential(){TUser user=user(8);TEmployee employee=new TEmployee();employee.setId(18);employee.setUserId(8);employee.setProfileVersion(4);employee.setPhone("13800000001");employee.setEmploymentStatus(EmployeeStatus.ACTIVE);TAccountCredential token=contactCredential(3,"13800000001");when(credentials.selectByDigest(anyString())).thenReturn(token);when(users.selectByPrimaryKeyForUpdate(8)).thenReturn(user);when(employees.selectByUserIdForUpdate(8)).thenReturn(employee);VerifyContactRequest request=new VerifyContactRequest();request.setCredential("raw");BusinessException ex=assertThrows(BusinessException.class,()->service.verifyContact(request));assertEquals(CodeEnum.PROFILE_VERSION_CONFLICT,ex.getCodeEnum());verify(credentials,never()).consumeByIdAndVersion(anyLong(),anyInt(),any());verify(employees,never()).markContactVerifiedByProfileVersion(anyInt(),anyInt(),anyString(),any());}
 @Test void breakGlassIsDefaultClosed(){BreakGlassRequest request=new BreakGlassRequest();request.setLoginAct("admin");request.setRecoveryKey("x".repeat(32));BusinessException ex=assertThrows(BusinessException.class,()->service.requestBreakGlass(request));assertEquals(CodeEnum.ACCESS_DENIED,ex.getCodeEnum());verify(credentials,never()).insert(any());}
 @Test void wrongBreakGlassKeyWritesOnlyDigestedRejectedAudit(){ReflectionTestUtils.setField(service,"breakGlassEnabled",true);ReflectionTestUtils.setField(service,"breakGlassKey","correct-recovery-key-for-test-000001");BreakGlassRequest request=new BreakGlassRequest();request.setLoginAct("admin");request.setRecoveryKey("wrong-recovery-key-for-test-0000001");BusinessException ex=assertThrows(BusinessException.class,()->service.requestBreakGlass(request));assertEquals(CodeEnum.ACCESS_DENIED,ex.getCodeEnum());verify(failureAudit).recordAnonymous(eq(AuditActionEnum.USER_RECOVERY_KEY_REJECTED),matches("[0-9a-f]{16}"),contains("BREAK_GLASS_KEY"));}
 @Test void breakGlassCompletionOnlyRecoversProtectedSystemAccount(){ReflectionTestUtils.setField(service,"breakGlassEnabled",true);TUser user=user(1);user.setLoginAct("admin");user.setAccountType(AccountType.SYSTEM);user.setProtectedAccount(true);user.setLoginPwd("oldHash");TAccountCredential token=credential(CredentialStatus.ISSUED,true);token.setUserId(1);token.setPurpose(CredentialPurpose.BREAK_GLASS);when(credentials.selectByDigest(anyString())).thenReturn(token);when(users.selectByPrimaryKeyForUpdate(1)).thenReturn(user);when(credentials.consumeByIdAndVersion(eq(1L),eq(0),any())).thenReturn(1);when(history.insert(any())).thenReturn(1);when(users.recoverProtectedAccountByExpected(eq(1),eq(0),nullable(String.class),any())).thenReturn(1);BreakGlassCompleteRequest request=new BreakGlassCompleteRequest();request.setCredential("raw");request.setNewPassword("Valid1A");service.completeBreakGlass(request);verify(users).recoverProtectedAccountByExpected(eq(1),eq(0),nullable(String.class),any());verify(securityMutations).authenticationChanged(1,null,"受保护账号应急恢复");}
 @Test void weakPasswordUsesStablePolicyCode(){TUser user=user(8);user.setLoginPwd("old");when(current.getCurrentUserId()).thenReturn(8);when(users.selectByPrimaryKeyForUpdate(8)).thenReturn(user);when(encoder.matches("old", "old")).thenReturn(true);BusinessException ex=assertThrows(BusinessException.class,()->service.changeOwn(change("old","weak")));assertEquals(CodeEnum.PASSWORD_POLICY_VIOLATION,ex.getCodeEnum());}
 private ForgotRequest forgot(String login){ForgotRequest q=new ForgotRequest();q.setLoginAct(login);return q;}private ActivateRequest activate(String c,String p){ActivateRequest q=new ActivateRequest();q.setCredential(c);q.setNewPassword(p);return q;}private ChangePasswordRequest change(String a,String b){ChangePasswordRequest q=new ChangePasswordRequest();q.setCurrentPassword(a);q.setNewPassword(b);return q;}
 private TAccountCredential contactCredential(int profileVersion,String phone){TAccountCredential token=credential(CredentialStatus.ISSUED,true);token.setPurpose(CredentialPurpose.PHONE_VERIFY);token.setTargetProfileVersion(profileVersion);token.setTargetValueDigest(ReflectionTestUtils.invokeMethod(service,"contactDigest",CredentialPurpose.PHONE_VERIFY,phone));return token;}
 private TUser user(int id){TUser u=new TUser();u.setId(id);u.setLoginAct("u"+id);u.setAccountStatus(AccountStatus.INVITED);u.setAccountType(AccountType.HUMAN);u.setVersion(0);return u;}private TAccountCredential credential(CredentialStatus s,boolean active){TAccountCredential c=new TAccountCredential();c.setId(1L);c.setUserId(8);c.setPurpose(CredentialPurpose.INVITATION);c.setStatus(s);c.setActiveMarker(active);c.setVersion(0);c.setExpiresAt(LocalDateTime.now().plusHours(1));return c;}
}
