package com.autodealer.crm.modules.identity.application.internal;

import com.autodealer.crm.modules.identity.application.api.CredentialDeliveryPort;
import com.autodealer.crm.modules.identity.application.api.CredentialService;
import com.autodealer.crm.modules.identity.application.api.enums.AccountStatus;
import com.autodealer.crm.modules.identity.application.api.enums.AccountType;
import com.autodealer.crm.modules.identity.application.api.enums.CredentialPurpose;
import com.autodealer.crm.modules.identity.application.api.enums.CredentialStatus;
import com.autodealer.crm.modules.identity.application.api.enums.EmployeeStatus;
import com.autodealer.crm.modules.identity.application.api.model.TUser;
import com.autodealer.crm.modules.identity.persistence.mapper.TAccountCredentialMapper;
import com.autodealer.crm.modules.identity.persistence.mapper.TAuthorizationGraphLockMapper;
import com.autodealer.crm.modules.identity.persistence.mapper.TEmployeeMapper;
import com.autodealer.crm.modules.identity.persistence.mapper.TPasswordHistoryMapper;
import com.autodealer.crm.modules.identity.persistence.mapper.TUserMapper;
import com.autodealer.crm.modules.identity.persistence.model.TAccountCredential;
import com.autodealer.crm.modules.identity.persistence.model.TEmployee;
import com.autodealer.crm.modules.identity.persistence.model.TPasswordHistory;
import com.autodealer.crm.modules.identity.application.api.security.CredentialDerivationCodec;

import com.autodealer.crm.modules.audit.application.api.AuditActionEnum;
import com.autodealer.crm.modules.audit.application.api.OperationAuditRecorder;
import com.autodealer.crm.modules.audit.application.api.SecurityFailureAuditService;
import com.autodealer.crm.modules.identity.application.api.security.CurrentUserProvider;
import com.autodealer.crm.shared.infrastructure.cache.RedisKeys;
import com.autodealer.crm.modules.identity.application.api.dto.credential.CredentialDtos.*;
import com.autodealer.crm.modules.identity.application.api.enums.*;
import com.autodealer.crm.shared.error.BusinessException;
import com.autodealer.crm.shared.infrastructure.cache.RedisManager;
import com.autodealer.crm.modules.identity.persistence.mapper.*;
import com.autodealer.crm.modules.identity.persistence.model.*;
import com.autodealer.crm.modules.identity.application.api.model.*;
import com.autodealer.crm.shared.error.CodeEnum;
import com.autodealer.crm.modules.identity.application.api.*;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.LocalDateTime;
import java.util.Objects;
import java.util.UUID;

@Service
public class CredentialServiceImpl implements CredentialService {
    private static final int HISTORY_LIMIT=5;
    private final TUserMapper userMapper; private final TAccountCredentialMapper credentialMapper;
    private final TEmployeeMapper employeeMapper;
    private final TPasswordHistoryMapper historyMapper; private final PasswordEncoder passwordEncoder;
    private final CredentialDeliveryPort deliveryPort; private final CurrentUserProvider currentUser;
    private final UserAuthorizationPolicy policy; private final RedisManager redis; private final OperationAuditRecorder audit;
    private final UserSecurityMutationCoordinator securityMutations;
    private final CredentialIssuanceService issuanceService; private final CredentialDerivationCodec derivationCodec;
    private final CredentialTokenDigester tokenDigester;
    private final SecurityFailureAuditService failureAudit;
    private final TAuthorizationGraphLockMapper graphLocks;
    @Value("${security.recovery.break-glass.enabled:false}") private boolean breakGlassEnabled;
    @Value("${security.recovery.break-glass.key:${RECOVERY_BREAK_GLASS_KEY:}}") private String breakGlassKey;
    @Value("${security.credential-rate-limit.enabled:true}") private boolean credentialRateLimitEnabled;
    public CredentialServiceImpl(TUserMapper userMapper,TAccountCredentialMapper credentialMapper,
      TPasswordHistoryMapper historyMapper,TEmployeeMapper employeeMapper,PasswordEncoder passwordEncoder,CredentialDeliveryPort deliveryPort,
      CurrentUserProvider currentUser,UserAuthorizationPolicy policy,RedisManager redis,OperationAuditRecorder audit,UserSecurityMutationCoordinator securityMutations,
      CredentialIssuanceService issuanceService,CredentialDerivationCodec derivationCodec,CredentialTokenDigester tokenDigester,SecurityFailureAuditService failureAudit,
      TAuthorizationGraphLockMapper graphLocks){
      this.userMapper=userMapper;this.credentialMapper=credentialMapper;this.historyMapper=historyMapper;this.passwordEncoder=passwordEncoder;
      this.employeeMapper=employeeMapper;this.deliveryPort=deliveryPort;this.currentUser=currentUser;this.policy=policy;this.redis=redis;this.audit=audit;this.securityMutations=securityMutations;
      this.issuanceService=issuanceService;this.derivationCodec=derivationCodec;this.tokenDigester=tokenDigester;this.failureAudit=failureAudit;this.graphLocks=graphLocks;}

    @Override @Transactional public CommandResult activate(ActivateRequest request){requireCredentialAttempt("ACTIVATE",request.getCredential(),10,900);TAccountCredential c=requireCredential(request.getCredential(),CredentialPurpose.INVITATION);TUser user=requireLockedUser(c.getUserId());TEmployee employee=requireLockedEmploymentEligible(user.getId());if(user.getAccountStatus()!=AccountStatus.INVITED)throw new BusinessException(CodeEnum.CREDENTIAL_INVALID);consume(c);if(employee.getEmploymentStatus()!=EmployeeStatus.PENDING)throw new BusinessException(CodeEnum.USER_LIFECYCLE_CONFLICT,"仅待入职员工可以激活邀请");changePassword(user,request.getNewPassword(),null,true,true,"ACTIVATION");if(employeeMapper.activatePendingByUserId(user.getId(),LocalDateTime.now())!=1)throw new BusinessException(CodeEnum.USER_LIFECYCLE_CONFLICT,"员工激活状态已变化");audit.recordAnonymous(AuditActionEnum.USER_ACTIVATION,String.valueOf(c.getUserId()),"SUCCESS","{\"purpose\":\"INVITATION\"}");return new CommandResult(true);}
    @Override public RequestAccepted forgot(ForgotRequest request){String loginAct=request.getLoginAct().trim();if(!withinPublicRate("FORGOT_ACCOUNT",loginAct,5,900,"FORGOT_SOURCE",20,900)){recordRateLimit("FORGOT",loginAct);return new RequestAccepted(true,"QUEUED");}TUser user=userMapper.selectByLoginAct(loginAct);if(user!=null&&user.getAccountStatus()!=AccountStatus.DISABLED&&!Boolean.TRUE.equals(user.getProtectedAccount())){TEmployee employee=employeeMapper.selectByUserId(user.getId());String phone=employee!=null&&Boolean.TRUE.equals(employee.getPhoneVerified())?employee.getPhone():null;String email=employee!=null&&Boolean.TRUE.equals(employee.getEmailVerified())?employee.getEmail():null;if(phone!=null||email!=null){if(!withinContactRates("FORGOT_CONTACT",phone,email,5,900)){recordRateLimit("FORGOT_CONTACT",loginAct);return new RequestAccepted(true,"QUEUED");}try{issue(user,CredentialPurpose.SELF_RESET,null,"SELF_SERVICE_RESET",phone,email,null,null,java.time.Duration.ofMinutes(5));audit.recordAnonymousQuietly(AuditActionEnum.USER_CREDENTIAL_ISSUE,String.valueOf(user.getId()),"SUCCESS","{\"purpose\":\"SELF_RESET\",\"deliveryStatus\":\"QUEUED\"}");}catch(RuntimeException ignored){/* 公开响应保持同形；独立签发事务已经回滚。 */}}}return new RequestAccepted(true,"QUEUED");}
    @Override @Transactional public CommandResult reset(ResetRequest request){requireCredentialAttempt("RESET",request.getCredential(),10,900);TAccountCredential c=requireCredential(request.getCredential(),CredentialPurpose.SELF_RESET,CredentialPurpose.ADMIN_RESET);TUser user=requireLockedUser(c.getUserId());requireLockedEmploymentEligible(user.getId());consume(c);changePassword(user,request.getNewPassword(),c.getIssuedBy(),false,c.getPurpose()==CredentialPurpose.ADMIN_RESET,"RESET");audit.recordAnonymous(AuditActionEnum.USER_CREDENTIAL_CONSUME,String.valueOf(c.getUserId()),"SUCCESS","{\"purpose\":\""+c.getPurpose().name()+"\"}");return new CommandResult(true);}
    @Override @Transactional public CommandResult firstChange(ChangePasswordRequest request){TUser user=requireLockedUser(currentUser.getCurrentUserId());requireOwnCredentialEligible(user);if(!Boolean.TRUE.equals(user.getMustChangePassword()))throw new BusinessException(CodeEnum.ACCESS_DENIED,"当前账号不需要首次改密");verifyCurrent(user,request.getCurrentPassword());changePassword(user,request.getNewPassword(),user.getId(),false,false,"FIRST_CHANGE");audit.record(AuditActionEnum.USER_PASSWORD_CHANGE,String.valueOf(user.getId()),"SUCCESS","{\"command\":\"FIRST_CHANGE\"}");return new CommandResult(true);}
    @Override @Transactional public CommandResult changeOwn(ChangePasswordRequest request){TUser user=requireLockedUser(currentUser.getCurrentUserId());requireOwnCredentialEligible(user);verifyCurrent(user,request.getCurrentPassword());changePassword(user,request.getNewPassword(),user.getId(),false,false,"OWN_CHANGE");audit.record(AuditActionEnum.USER_PASSWORD_CHANGE,String.valueOf(user.getId()),"SUCCESS","{\"command\":\"OWN_CHANGE\"}");return new CommandResult(true);}
    @Override @Transactional public ManagedDeliveryResult reinvite(Integer userId,ManagedRequest request){requireSourceRate("REINVITE",20,3600);TUser user=requireManaged(userId);TEmployee employee=requireEmploymentEligible(userId);requireManagedTargetRate("REINVITE",userId,employee,5,3600);if(user.getAccountStatus()!=AccountStatus.INVITED)throw new BusinessException(CodeEnum.OPERATION_FAILED,"仅待激活账号可以重发邀请");if(userMapper.incrementAccountVersionIfInvited(userId,request.getAccountVersion())!=1)throw new BusinessException(CodeEnum.ACCOUNT_VERSION_CONFLICT);String status=issue(user,CredentialPurpose.INVITATION,currentUser.getCurrentUserId(),request.getReason(),employee.getPhone(),employee.getEmail(),null,null,java.time.Duration.ofMinutes(5));audit.record(AuditActionEnum.USER_INVITATION_ISSUE,String.valueOf(userId),"SUCCESS","{\"purpose\":\"INVITATION\",\"command\":\"REINVITE\"}");return new ManagedDeliveryResult(deliveryAccepted(status),status);}
    @Override @Transactional public PasswordResetDeliveryResult adminReset(Integer userId,ManagedRequest request){requireSourceRate("ADMIN_RESET",20,3600);lockGraph("ORGANIZATION_HIERARCHY");lockGraph("REPORTING_GRAPH");lockGraph("AVAILABLE_ADMIN_GUARD");TUser user=requireAuthorizationManaged(userId);TEmployee employee=requireEmploymentEligible(userId);requireManagedTargetRate("ADMIN_RESET",userId,employee,5,3600);boolean administrator=userMapper.selectRolesByUserId(userId).stream().anyMatch(role->"admin".equals(role.getRole()));if(administrator&&userMapper.countAvailableAdminUsersExcluding(userId)<1)throw new BusinessException(CodeEnum.LAST_AVAILABLE_ADMIN_REQUIRED,"不能重置最后一个可用普通管理员的密码");if(userMapper.updateMustChangePasswordByExpected(userId,request.getAccountVersion(),true)!=1)throw new BusinessException(CodeEnum.ACCOUNT_VERSION_CONFLICT);securityMutations.authenticationChanged(userId,"管理员重置密码");String status=issue(user,CredentialPurpose.ADMIN_RESET,currentUser.getCurrentUserId(),request.getReason(),employee.getPhone(),employee.getEmail(),null,null,java.time.Duration.ofMinutes(5));audit.record(AuditActionEnum.USER_PASSWORD_RESET_ISSUE,String.valueOf(userId),"SUCCESS","{\"command\":\"ADMIN_RESET\"}");return new PasswordResetDeliveryResult(deliveryAccepted(status),status,true);}
    @Override @Transactional public ManagedDeliveryResult issueInvitation(Integer userId,String reason){requireSourceRate("REHIRE_INVITATION",20,3600);TUser user=requireUser(userId);TEmployee employee=requireEmploymentEligible(userId);requireManagedTargetRate("REHIRE_INVITATION",userId,employee,5,3600);if(user.getAccountStatus()!=AccountStatus.INVITED)throw new BusinessException(CodeEnum.USER_LIFECYCLE_CONFLICT,"仅待激活账号可以签发邀请");String status=issue(user,CredentialPurpose.INVITATION,currentUser.getCurrentUserId(),reason,employee.getPhone(),employee.getEmail(),null,null,java.time.Duration.ofMinutes(5));audit.record(AuditActionEnum.USER_INVITATION_ISSUE,String.valueOf(userId),"SUCCESS","{\"purpose\":\"INVITATION\",\"command\":\"REHIRE\"}");return new ManagedDeliveryResult(deliveryAccepted(status),status);}
    @Override @Transactional public void revokeAll(Integer userId){credentialMapper.revokeAllActive(userId,LocalDateTime.now());}
    @Override @Transactional public ManagedDeliveryResult requestContactVerification(ContactVerificationRequest request){Integer userId=currentUser.getCurrentUserId();requireSourceRate("CONTACT_VERIFY_"+request.getChannel().name(),20,3600);TUser user=requireLockedUser(userId);if(user.getAccountType()!=AccountType.HUMAN||Boolean.TRUE.equals(user.getProtectedAccount()))throw new BusinessException(CodeEnum.ACCESS_DENIED,"受保护账号不使用普通联系方式验证");TEmployee employee=requireLockedEmploymentEligible(userId);CredentialPurpose purpose=request.getChannel()==ContactChannel.PHONE?CredentialPurpose.PHONE_VERIFY:CredentialPurpose.EMAIL_VERIFY;String phone=purpose==CredentialPurpose.PHONE_VERIFY?employee.getPhone():null;String email=purpose==CredentialPurpose.EMAIL_VERIFY?employee.getEmail():null;String target=phone!=null?phone:email;if(target==null)throw new BusinessException(CodeEnum.PARAM_ERROR,"当前联系方式为空");if(!withinRate("CONTACT_USER_"+request.getChannel().name(),String.valueOf(userId),5,3600)||!withinRate("CONTACT_TARGET_"+request.getChannel().name(),target,5,3600)){recordRateLimit("CONTACT_TARGET",target);throw new BusinessException(CodeEnum.CREDENTIAL_RATE_LIMITED);}int profileVersion=employee.getProfileVersion()==null?0:employee.getProfileVersion();String status=issue(user,purpose,userId,"CONTACT_VERIFICATION",phone,email,contactDigest(purpose,target),profileVersion,java.time.Duration.ofMinutes(5));audit.record(AuditActionEnum.USER_CONTACT_VERIFICATION_ISSUE,String.valueOf(userId),"SUCCESS","{\"channel\":\""+request.getChannel().name()+"\",\"profileVersion\":"+profileVersion+"}");return new ManagedDeliveryResult(deliveryAccepted(status),status);}
    @Override @Transactional public CommandResult verifyContact(VerifyContactRequest request){requireCredentialAttempt("VERIFY_CONTACT",request.getCredential(),10,900);TAccountCredential c=requireCredential(request.getCredential(),CredentialPurpose.PHONE_VERIFY,CredentialPurpose.EMAIL_VERIFY);TUser user=requireLockedUser(c.getUserId());TEmployee employee=requireLockedEmploymentEligible(user.getId());String channel=c.getPurpose()==CredentialPurpose.PHONE_VERIFY?ContactChannel.PHONE.name():ContactChannel.EMAIL.name();String currentTarget=c.getPurpose()==CredentialPurpose.PHONE_VERIFY?employee.getPhone():employee.getEmail();int currentProfileVersion=employee.getProfileVersion()==null?0:employee.getProfileVersion();if(currentTarget==null||!Objects.equals(c.getTargetValueDigest(),contactDigest(c.getPurpose(),currentTarget))||!Objects.equals(c.getTargetProfileVersion(),currentProfileVersion))throw new BusinessException(CodeEnum.PROFILE_VERSION_CONFLICT,"联系方式已经变化，请重新验证");consume(c);if(employeeMapper.markContactVerifiedByProfileVersion(employee.getId(),currentProfileVersion,channel,LocalDateTime.now())!=1)throw new BusinessException(CodeEnum.PROFILE_VERSION_CONFLICT,"联系方式已经变化，请重新验证");audit.recordAnonymous(AuditActionEnum.USER_CONTACT_VERIFICATION_COMPLETE,String.valueOf(user.getId()),"SUCCESS","{\"channel\":\""+channel+"\",\"profileVersion\":"+currentProfileVersion+"}");return new CommandResult(true);}
    @Override @Transactional public ManagedDeliveryResult requestBreakGlass(BreakGlassRequest request){String loginAct=request.getLoginAct().trim();if(!withinPublicRate("BREAK_GLASS_ACCOUNT",loginAct,3,3600,"BREAK_GLASS_SOURCE",10,3600)){recordRateLimit("BREAK_GLASS_REQUEST",loginAct);throw new BusinessException(CodeEnum.CREDENTIAL_RATE_LIMITED);}if(!breakGlassEnabled||breakGlassKey==null||breakGlassKey.length()<32||!constantTimeEquals(breakGlassKey,request.getRecoveryKey())){recordRecoveryKeyRejected(loginAct,"BREAK_GLASS_KEY");throw new BusinessException(CodeEnum.ACCESS_DENIED,"应急恢复未启用或恢复密钥无效");}TUser user=userMapper.selectByLoginAct(loginAct);if(!isFixedRecovery(user)){recordRecoveryKeyRejected(loginAct,"BREAK_GLASS_TARGET");throw new BusinessException(CodeEnum.ACCESS_DENIED,"应急恢复目标无效");}if(!withinContactRates("BREAK_GLASS_CONTACT",user.getPhone(),user.getEmail(),3,3600)){recordRateLimit("BREAK_GLASS_CONTACT",loginAct);throw new BusinessException(CodeEnum.CREDENTIAL_RATE_LIMITED);}String status=issue(user,CredentialPurpose.BREAK_GLASS,null,"PROTECTED_ACCOUNT_BREAK_GLASS",user.getPhone(),user.getEmail(),null,null,java.time.Duration.ofMinutes(5));audit.recordAnonymous(AuditActionEnum.USER_RECOVERY_BREAK_GLASS_ISSUE,String.valueOf(user.getId()),"SUCCESS","{\"deliveryStatus\":\""+status+"\"}");return new ManagedDeliveryResult(deliveryAccepted(status),status);}
    @Override @Transactional public CommandResult completeBreakGlass(BreakGlassCompleteRequest request){requireCredentialAttempt("BREAK_GLASS_COMPLETE",request.getCredential(),5,3600);if(!breakGlassEnabled)throw new BusinessException(CodeEnum.ACCESS_DENIED,"应急恢复未启用");TAccountCredential c=requireCredential(request.getCredential(),CredentialPurpose.BREAK_GLASS);TUser user=requireLockedUser(c.getUserId());if(!isFixedRecovery(user))throw new BusinessException(CodeEnum.ACCESS_DENIED,"应急恢复目标无效");consume(c);recoverProtectedPassword(user,request.getNewPassword());audit.recordAnonymous(AuditActionEnum.USER_RECOVERY_BREAK_GLASS_COMPLETE,String.valueOf(user.getId()),"SUCCESS","{\"command\":\"BREAK_GLASS\"}");return new CommandResult(true);}
    @Override @Transactional public ManagedDeliveryResult issueDegradedAdminRecovery(Integer userId,String reason){TUser user=requireUser(userId);TEmployee employee=requireEmploymentEligible(userId);CredentialPurpose purpose=user.getAccountStatus()==AccountStatus.INVITED?CredentialPurpose.INVITATION:CredentialPurpose.ADMIN_RESET;String status=issue(user,purpose,null,reason,employee.getPhone(),employee.getEmail(),null,null,java.time.Duration.ofMinutes(5));audit.recordAnonymous(AuditActionEnum.USER_DEGRADED_ADMIN_RECOVERY,String.valueOf(userId),"SUCCESS","{\"purpose\":\""+purpose.name()+"\",\"deliveryStatus\":\""+status+"\"}");return new ManagedDeliveryResult(deliveryAccepted(status),status);}

    private TUser requireManaged(Integer id){TUser user=requireUser(id);policy.requireManage(user);return user;}
    private TUser requireAuthorizationManaged(Integer id){TUser user=requireUser(id);policy.requireAuthorizationManage(user);return user;}
    private String issue(TUser user,CredentialPurpose purpose,Integer operator,String reason){DeliveryTarget target=deliveryTarget(user);return issue(user,purpose,operator,reason,target.phone(),target.email());}
    private String issue(TUser user,CredentialPurpose purpose,Integer operator,String reason,String phone,String email){return issue(user,purpose,operator,reason,phone,email,null,null,java.time.Duration.ZERO);}
    private String issue(TUser user,CredentialPurpose purpose,Integer operator,String reason,String phone,String email,String targetValueDigest,Integer targetProfileVersion){return issue(user,purpose,operator,reason,phone,email,targetValueDigest,targetProfileVersion,java.time.Duration.ZERO);}
    private String issue(TUser user,CredentialPurpose purpose,Integer operator,String reason,String phone,String email,String targetValueDigest,Integer targetProfileVersion,java.time.Duration cooldown){CredentialDeliveryPort.DeliveryStatus validation;try{validation=deliveryPort.validateTarget(phone,email);}catch(RuntimeException exception){throw new BusinessException(CodeEnum.CREDENTIAL_DELIVERY_FAILED,"安全通知渠道配置检查失败");}if(!"QUEUED".equals(validation.code()))throw new BusinessException(CodeEnum.CREDENTIAL_DELIVERY_FAILED,"安全通知渠道未配置或缺少联系方式");LocalDateTime now=LocalDateTime.now().withNano(0);String messageId=UUID.randomUUID().toString();String nonce=derivationCodec.newNonce();String deliveryCommitment=derivationCodec.deliveryCommitment(messageId,purpose,nonce);issuanceService.enqueue(user.getId(),purpose,deliveryCommitment,messageId,nonce,derivationCodec.contactDigest("PHONE",phone),derivationCodec.contactDigest("EMAIL",email),operator,reason,targetValueDigest,targetProfileVersion,now,credentialLifetime(purpose),cooldown);return "QUEUED";}
    private boolean deliveryAccepted(String status){return "QUEUED".equals(status)||"CAPTURED".equals(status)||"WEBHOOK_DELIVERED".equals(status)||"EMAIL_SENT".equals(status)||"SMS_SENT".equals(status);}
    private TAccountCredential requireCredential(String raw,CredentialPurpose...purposes){String tokenDigest=digest(raw);String resource=tokenDigest.substring(0,16);TAccountCredential c=credentialMapper.selectByDigest(tokenDigest);if(c==null){recordCredentialRejected(resource,"INVALID");throw new BusinessException(CodeEnum.CREDENTIAL_INVALID);}boolean purpose=false;for(CredentialPurpose p:purposes)purpose|=p==c.getPurpose();if(!purpose){recordCredentialRejected(resource,"PURPOSE_MISMATCH");throw new BusinessException(CodeEnum.CREDENTIAL_INVALID);}if(c.getStatus()!=CredentialStatus.ISSUED||!Boolean.TRUE.equals(c.getActiveMarker())){recordCredentialRejected(resource,"ALREADY_USED_OR_REVOKED");throw new BusinessException(CodeEnum.CREDENTIAL_ALREADY_USED);}if(c.getExpiresAt()==null||!c.getExpiresAt().isAfter(LocalDateTime.now())){recordCredentialRejected(resource,"EXPIRED");throw new BusinessException(CodeEnum.CREDENTIAL_EXPIRED);}return c;}
    private void consume(TAccountCredential c){if(credentialMapper.consumeByIdAndVersion(c.getId(),c.getVersion(),LocalDateTime.now())!=1){String resource=c.getTokenDigest()==null?"UNKNOWN":c.getTokenDigest().substring(0,Math.min(16,c.getTokenDigest().length()));TAccountCredential latest=credentialMapper.selectByDigest(c.getTokenDigest());if(latest!=null&&latest.getExpiresAt()!=null&&!latest.getExpiresAt().isAfter(LocalDateTime.now())){recordCredentialRejected(resource,"EXPIRED_DURING_CONSUME");throw new BusinessException(CodeEnum.CREDENTIAL_EXPIRED);}recordCredentialRejected(resource,"CONCURRENT_OR_REPEATED_CONSUME");throw new BusinessException(CodeEnum.CREDENTIAL_ALREADY_USED);}}
    private void verifyCurrent(TUser user,String raw){if(!passwordEncoder.matches(raw,user.getLoginPwd()))throw new BusinessException(CodeEnum.AUTH_LOGIN_FAILED);}
    private void changePassword(TUser user,String raw,Integer operator,boolean activation,boolean mustChange,String reason){validatePolicy(raw);Integer userId=user.getId();if(passwordEncoder.matches(raw,user.getLoginPwd())||historyMapper.selectRecent(userId,HISTORY_LIMIT).stream().anyMatch(h->passwordEncoder.matches(raw,h.getPasswordHash())))throw new BusinessException(CodeEnum.PASSWORD_HISTORY_REUSED);TPasswordHistory h=new TPasswordHistory();h.setUserId(userId);h.setPasswordHash(user.getLoginPwd());h.setChangedBy(operator);h.setChangeReason(reason);h.setChangedAt(LocalDateTime.now());if(user.getLoginPwd()!=null&&historyMapper.insert(h)!=1)throw new BusinessException(CodeEnum.OPERATION_FAILED,"密码历史保存失败");String encoded=passwordEncoder.encode(raw);LocalDateTime expiresAt=LocalDateTime.now().plusDays(90);int changed=activation?userMapper.activateCredentialState(userId,user.getVersion(),encoded,mustChange,expiresAt):userMapper.updatePasswordCredentialState(userId,user.getVersion(),encoded,mustChange,expiresAt);if(changed!=1)throw new BusinessException(CodeEnum.ACCOUNT_VERSION_CONFLICT,"账号状态已变化");credentialMapper.revokeAllActive(userId,LocalDateTime.now());if(activation)securityMutations.accessChanged(userId,operator,"密码变化");else securityMutations.authenticationChanged(userId,operator,"密码变化");}
    private void recoverProtectedPassword(TUser user,String raw){validatePolicy(raw);Integer userId=user.getId();if(passwordEncoder.matches(raw,user.getLoginPwd())||historyMapper.selectRecent(userId,HISTORY_LIMIT).stream().anyMatch(h->passwordEncoder.matches(raw,h.getPasswordHash())))throw new BusinessException(CodeEnum.PASSWORD_HISTORY_REUSED);TPasswordHistory h=new TPasswordHistory();h.setUserId(userId);h.setPasswordHash(user.getLoginPwd());h.setChangeReason("BREAK_GLASS");h.setChangedAt(LocalDateTime.now());if(user.getLoginPwd()!=null&&historyMapper.insert(h)!=1)throw new BusinessException(CodeEnum.OPERATION_FAILED,"密码历史保存失败");if(userMapper.recoverProtectedAccountByExpected(userId,user.getVersion(),passwordEncoder.encode(raw),LocalDateTime.now().plusDays(90))!=1)throw new BusinessException(CodeEnum.ACCOUNT_VERSION_CONFLICT,"恢复账号状态已变化");credentialMapper.revokeAllActive(userId,LocalDateTime.now());securityMutations.authenticationChanged(userId,null,"受保护账号应急恢复");}
    private void validatePolicy(String value){if(value==null||value.length()<6||value.length()>16||!value.matches(".*[a-z].*")||!value.matches(".*[A-Z].*")||!value.matches(".*\\d.*"))throw new BusinessException(CodeEnum.PASSWORD_POLICY_VIOLATION);}
    private TUser requireUser(Integer id){TUser user=userMapper.selectByPrimaryKey(id);if(user==null)throw new BusinessException(CodeEnum.NOT_FOUND,"用户不存在");return user;}
    private TUser requireLockedUser(Integer id){TUser user=userMapper.selectByPrimaryKeyForUpdate(id);if(user==null)throw new BusinessException(CodeEnum.NOT_FOUND,"用户不存在");return user;}
    private TEmployee requireEmploymentEligible(Integer userId){TEmployee employee=employeeMapper.selectByUserId(userId);if(employee==null)throw new BusinessException(CodeEnum.NOT_FOUND,"员工档案不存在");if(employee.getEmploymentStatus()==EmployeeStatus.LEFT)throw new BusinessException(CodeEnum.USER_LIFECYCLE_CONFLICT,"已离职员工必须先完成返聘");return employee;}
    private TEmployee requireLockedEmploymentEligible(Integer userId){TEmployee employee=employeeMapper.selectByUserIdForUpdate(userId);if(employee==null)throw new BusinessException(CodeEnum.NOT_FOUND,"员工档案不存在");if(employee.getEmploymentStatus()==EmployeeStatus.LEFT)throw new BusinessException(CodeEnum.USER_LIFECYCLE_CONFLICT,"已离职员工必须先完成返聘");return employee;}
    private void requireOwnCredentialEligible(TUser user){if(user.getAccountType()==AccountType.SYSTEM&&Boolean.TRUE.equals(user.getProtectedAccount()))return;requireLockedEmploymentEligible(user.getId());}
    private String contactDigest(CredentialPurpose purpose,String value){return digest("CONTACT:"+purpose.name()+":"+value);}
    private void requireCredentialAttempt(String scope,String credential,int limit,long seconds){if(withinPublicRate(scope+"_TOKEN",credential,limit,seconds,scope+"_SOURCE",limit*2,seconds))return;recordRateLimit(scope,credential);throw new BusinessException(CodeEnum.CREDENTIAL_RATE_LIMITED);}
    private void requireSourceRate(String scope,int limit,long seconds){if(withinRate(scope+"_SOURCE",requestSource(),limit,seconds))return;recordRateLimit(scope+"_SOURCE",requestSource());throw new BusinessException(CodeEnum.CREDENTIAL_RATE_LIMITED);}
    private void requireManagedTargetRate(String scope,Integer userId,TEmployee employee,int limit,long seconds){boolean allowed=withinRate(scope+"_USER",String.valueOf(userId),limit,seconds)&&withinContactRates(scope+"_CONTACT",employee==null?null:employee.getPhone(),employee==null?null:employee.getEmail(),limit,seconds);if(allowed)return;recordRateLimit(scope,String.valueOf(userId));throw new BusinessException(CodeEnum.CREDENTIAL_RATE_LIMITED);}
    private boolean withinContactRates(String scope,String phone,String email,int limit,long seconds){boolean allowed=true;if(phone!=null&&!phone.isBlank())allowed=withinRate(scope+"_PHONE",phone,limit,seconds)&&allowed;if(email!=null&&!email.isBlank())allowed=withinRate(scope+"_EMAIL",email,limit,seconds)&&allowed;return allowed;}
    private boolean withinPublicRate(String subjectScope,String subject,int subjectLimit,long subjectSeconds,String sourceScope,int sourceLimit,long sourceSeconds){boolean subjectAllowed=withinRate(subjectScope,subject,subjectLimit,subjectSeconds);boolean sourceAllowed=withinRate(sourceScope,requestSource(),sourceLimit,sourceSeconds);return subjectAllowed&&sourceAllowed;}
    private boolean withinRate(String scope,String subject,int limit,long seconds){if(!credentialRateLimitEnabled)return true;String subjectDigest=digest("RATE:"+scope+":"+(subject==null?"<NULL>":subject.trim())).substring(0,32);Long count=redis.incrementSlidingWindow(RedisKeys.credentialRateLimit(scope,subjectDigest),seconds);return count!=null&&count<=limit;}
    private void recordRateLimit(String scope,String subject){String resource=digest("RATE_AUDIT:"+scope+":"+(subject==null?"<NULL>":subject)).substring(0,16);failureAudit.recordAnonymous(AuditActionEnum.USER_CREDENTIAL_RATE_LIMIT,resource,"{\"scope\":\""+scope+"\"}");}
    private void recordCredentialRejected(String resource,String reason){failureAudit.recordAnonymous(AuditActionEnum.USER_CREDENTIAL_ATTEMPT_REJECTED,resource,"{\"reason\":\""+reason+"\"}");}
    private void recordRecoveryKeyRejected(String loginAct,String reason){String resource=digest("RECOVERY_AUDIT:"+(loginAct==null?"<NULL>":loginAct)).substring(0,16);failureAudit.recordAnonymous(AuditActionEnum.USER_RECOVERY_KEY_REJECTED,resource,"{\"reason\":\""+reason+"\"}");}
    private String requestSource(){if(RequestContextHolder.getRequestAttributes() instanceof ServletRequestAttributes attributes){String remote=attributes.getRequest().getRemoteAddr();if(remote!=null&&!remote.isBlank())return remote;}return "INTERNAL";}
    private java.time.Duration credentialLifetime(CredentialPurpose purpose){return switch(purpose){case INVITATION->java.time.Duration.ofHours(48);case PHONE_VERIFY,EMAIL_VERIFY->java.time.Duration.ofMinutes(30);case BREAK_GLASS->java.time.Duration.ofMinutes(15);default->java.time.Duration.ofHours(1);};}
    private boolean constantTimeEquals(String expected,String actual){if(expected==null||actual==null)return false;return MessageDigest.isEqual(expected.getBytes(StandardCharsets.UTF_8),actual.getBytes(StandardCharsets.UTF_8));}
    private boolean isFixedRecovery(TUser user){return user!=null&&Objects.equals(user.getId(),1)&&"admin".equals(user.getLoginAct())&&user.getAccountType()==AccountType.SYSTEM&&Boolean.TRUE.equals(user.getProtectedAccount());}
    private DeliveryTarget deliveryTarget(TUser user){if(user.getAccountType()==AccountType.HUMAN){TEmployee employee=employeeMapper.selectByUserId(user.getId());return employee==null?new DeliveryTarget(null,null):new DeliveryTarget(employee.getPhone(),employee.getEmail());}return new DeliveryTarget(user.getPhone(),user.getEmail());}
    private record DeliveryTarget(String phone,String email){}
    private void lockGraph(String name){if(!name.equals(graphLocks.lockByName(name)))throw new IllegalStateException("凭据治理图锁缺失: "+name);}
    private String digest(String raw){return tokenDigester.digest(raw);}
}
