package com.autodealer.crm.modules.identity.web;

import com.autodealer.crm.shared.infrastructure.cache.RedisKeys;
import com.autodealer.crm.integration.BackendIntegrationTestBase;
import com.autodealer.crm.modules.identity.application.api.model.TUser;
import tools.jackson.databind.JsonNode;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.http.*;
import org.springframework.test.web.servlet.MvcResult;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.when;
import static org.mockito.Mockito.doReturn;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

class UserSessionIntegrationTest extends BackendIntegrationTestBase {
 @BeforeEach void cleanSessions(){jdbcTemplate.update("DELETE FROM t_user_session");jdbcTemplate.update("UPDATE t_user SET session_revision=0");}
 @Test void multipleDevicesCoexistAndCurrentSessionIsRecognized() throws Exception {String first=loginAsAdmin();String second=loginAsAdmin();JsonNode data=getOwn(second);assertEquals(2,data.path("sessions").size());assertEquals(1,countCurrent(data));assertTrue(data.path("sessions").get(0).has("deviceSummary"));assertFalse(data.toString().contains("tokenDigest"));assertFalse(data.toString().contains("192.168."));}
 @Test void selectiveRevocationLeavesOtherDeviceValid() throws Exception {String first=loginAsAdmin();String second=loginAsAdmin();JsonNode before=getOwn(second);JsonNode old=firstNonCurrent(before);String body="{\"sessionRevision\":"+before.path("sessionRevision").asLong()+",\"reason\":\"设备遗失\"}";mockMvc.perform(post("/api/me/sessions/"+old.path("id").asText()+"/revoke").header(HttpHeaders.AUTHORIZATION,second).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk()).andExpect(jsonPath("$.data.sessions.length()").value(1));mockMvc.perform(get("/api/login/free").header(HttpHeaders.AUTHORIZATION,first)).andExpect(status().isUnauthorized());mockMvc.perform(get("/api/login/free").header(HttpHeaders.AUTHORIZATION,second)).andExpect(status().isOk());}
 @Test void maximumConcurrentSessionsDeterministicallyKeepsFiveNewest() throws Exception {String token=null;for(int i=0;i<6;i++)token=loginAsAdmin();JsonNode data=getOwn(token);assertEquals(5,data.path("sessions").size());assertEquals(1,countCurrent(data));}
 @Test void managerCanViewSubordinateButCannotUseManagedEndpointForSelf() throws Exception {loginAs("zhangsan","123456",2);String admin=loginAsQualifiedAdmin();mockMvc.perform(get("/api/users/2/sessions").header(HttpHeaders.AUTHORIZATION,admin)).andExpect(status().isOk()).andExpect(jsonPath("$.data.targetUserId").value(2));mockMvc.perform(get("/api/users/"+QUALIFIED_ADMIN_USER_ID+"/sessions").header(HttpHeaders.AUTHORIZATION,admin)).andExpect(status().isForbidden());}
 @Test void redisDeleteFalseDoesNotReturnFalseSuccess() throws Exception {String first=loginAsAdmin();String second=loginAsAdmin();JsonNode data=getOwn(second);JsonNode old=firstNonCurrent(data);when(redisManager.delete(RedisKeys.userSession(old.path("id").asText()))).thenReturn(false);String body="{\"sessionRevision\":"+data.path("sessionRevision").asLong()+",\"reason\":\"风险处置\"}";mockMvc.perform(post("/api/me/sessions/"+old.path("id").asText()+"/revoke").header(HttpHeaders.AUTHORIZATION,second).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isServiceUnavailable()).andExpect(jsonPath("$.code").value(635));}
 @Test void legacyOnlyRevokeAllRemovesCurrentLegacySession() throws Exception {String legacy=buildDirectToken(admin());JsonNode before=getOwn(legacy);assertTrue(contains(before.path("allowedActions"),"REVOKE_ALL"));String body=body(before,"清理旧设备");mockMvc.perform(post("/api/me/sessions/revoke-all").header(HttpHeaders.AUTHORIZATION,legacy).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk());mockMvc.perform(get("/api/me/sessions").header(HttpHeaders.AUTHORIZATION,legacy)).andExpect(status().isUnauthorized());}
 @Test void mixedNewCurrentRevokeOthersAlsoRemovesLegacyKey() throws Exception {String current=loginAsAdmin();String legacy=buildDirectToken(admin());JsonNode before=getOwn(current);assertTrue(contains(before.path("allowedActions"),"REVOKE_OTHERS"));mockMvc.perform(post("/api/me/sessions/revoke-others").header(HttpHeaders.AUTHORIZATION,current).contentType(MediaType.APPLICATION_JSON).content(body(before,"清理其他设备"))).andExpect(status().isOk());mockMvc.perform(get("/api/me/sessions").header(HttpHeaders.AUTHORIZATION,current)).andExpect(status().isOk());mockMvc.perform(get("/api/me/sessions").header(HttpHeaders.AUTHORIZATION,legacy)).andExpect(status().isUnauthorized());}
 @Test void legacyCurrentRevokeOthersKeepsLegacyAndRevokesAllNewFacts() throws Exception {String newer=loginAsAdmin();String legacy=buildDirectToken(admin());JsonNode before=getOwn(legacy);mockMvc.perform(post("/api/me/sessions/revoke-others").header(HttpHeaders.AUTHORIZATION,legacy).contentType(MediaType.APPLICATION_JSON).content(body(before,"旧设备保留"))).andExpect(status().isOk());mockMvc.perform(get("/api/me/sessions").header(HttpHeaders.AUTHORIZATION,legacy)).andExpect(status().isOk());mockMvc.perform(get("/api/me/sessions").header(HttpHeaders.AUTHORIZATION,newer)).andExpect(status().isUnauthorized());}
 @Test void legacyDeleteFalseReturns503AndStable635() throws Exception {String legacy=buildDirectToken(admin());JsonNode before=getOwn(legacy);doReturn(false).when(redisManager).delete(RedisKeys.userLogin(1));mockMvc.perform(post("/api/me/sessions/revoke-all").header(HttpHeaders.AUTHORIZATION,legacy).contentType(MediaType.APPLICATION_JSON).content(body(before,"缓存故障"))).andExpect(status().isServiceUnavailable()).andExpect(jsonPath("$.code").value(635));}
 @Test void selectedSessionErrorsExposeStable631To634Statuses() throws Exception {String first=loginAsAdmin();String second=loginAsAdmin();JsonNode before=getOwn(second);JsonNode old=firstNonCurrent(before);String revision=String.valueOf(before.path("sessionRevision").asLong());mockMvc.perform(post("/api/me/sessions/not-a-session/revoke").header(HttpHeaders.AUTHORIZATION,second).contentType(MediaType.APPLICATION_JSON).content("{\"sessionRevision\":"+revision+",\"reason\":\"不存在\"}")).andExpect(status().isNotFound()).andExpect(jsonPath("$.code").value(631));mockMvc.perform(post("/api/me/sessions/"+old.path("id").asText()+"/revoke").header(HttpHeaders.AUTHORIZATION,second).contentType(MediaType.APPLICATION_JSON).content("{\"sessionRevision\":0,\"reason\":\"过期版本\"}")).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value(634));jdbcTemplate.update("UPDATE t_user_session SET revoked_at=?,revoked_by=?,revoke_reason=?,revoke_type=? WHERE session_id=?",LocalDateTime.now(),1,"测试撤销","SELF_ONE",old.path("id").asText());mockMvc.perform(post("/api/me/sessions/"+old.path("id").asText()+"/revoke").header(HttpHeaders.AUTHORIZATION,second).contentType(MediaType.APPLICATION_JSON).content("{\"sessionRevision\":"+revision+",\"reason\":\"重复撤销\"}")).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value(632));LocalDateTime now=LocalDateTime.now();jdbcTemplate.update("UPDATE t_user_session SET revoked_at=NULL,revoked_by=NULL,revoke_reason=NULL,revoke_type=NULL,login_time=?,last_activity_time=?,idle_expires_at=?,absolute_expires_at=? WHERE session_id=?",now.minusMinutes(10),now.minusMinutes(9),now.minusMinutes(2),now.minusMinutes(1),old.path("id").asText());mockMvc.perform(post("/api/me/sessions/"+old.path("id").asText()+"/revoke").header(HttpHeaders.AUTHORIZATION,second).contentType(MediaType.APPLICATION_JSON).content("{\"sessionRevision\":"+revision+",\"reason\":\"过期会话\"}")).andExpect(status().isGone()).andExpect(jsonPath("$.code").value(633));}
 @Test void missingManagedTargetReturns404() throws Exception {String admin=loginAsQualifiedAdmin();mockMvc.perform(get("/api/users/999999/sessions").header(HttpHeaders.AUTHORIZATION,admin)).andExpect(status().isNotFound());}
 private JsonNode getOwn(String token)throws Exception{MvcResult result=mockMvc.perform(get("/api/me/sessions").header(HttpHeaders.AUTHORIZATION,token)).andExpect(status().isOk()).andReturn();return objectMapper.readTree(result.getResponse().getContentAsString()).path("data");}
 private int countCurrent(JsonNode data){int count=0;for(JsonNode item:data.path("sessions"))if(item.path("current").asBoolean())count++;return count;}
 private JsonNode firstNonCurrent(JsonNode data){for(JsonNode item:data.path("sessions"))if(!item.path("current").asBoolean())return item;throw new AssertionError("缺少其他会话");}
 private String body(JsonNode data,String reason){return "{\"sessionRevision\":"+data.path("sessionRevision").asLong()+",\"reason\":\""+reason+"\"}";}
 private boolean contains(JsonNode values,String expected){for(JsonNode value:values)if(expected.equals(value.asText()))return true;return false;}
 private TUser admin(){TUser user=new TUser();user.setId(1);user.setLoginAct("admin");return user;}
}
